//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/core/_DelayedToString.java
//


#include "J2ObjC_source.h"
#include "_DelayedConversionToString.h"
#include "_DelayedToString.h"
#include "java/lang/Integer.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/core/_DelayedToString.java"


#line 19
@implementation FreemarkerCore_DelayedToString

- (instancetype)initWithId:(id)object {
  FreemarkerCore_DelayedToString_initWithId_(self, object);
  return self;
}


#line 25
- (instancetype)initWithInt:(jint)object {
  FreemarkerCore_DelayedToString_initWithInt_(self, object);
  return self;
}


#line 29
- (NSString *)doConversionWithId:(id)obj {
  return NSString_valueOf_(obj);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithId:", "_DelayedToString", NULL, 0x1, NULL, NULL },
    { "initWithInt:", "_DelayedToString", NULL, 0x1, NULL, NULL },
    { "doConversionWithId:", "doConversion", "Ljava.lang.String;", 0x4, NULL, NULL },
  };
  static const J2ObjcClassInfo _FreemarkerCore_DelayedToString = { 2, "_DelayedToString", "freemarker.core", NULL, 0x1, 3, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_FreemarkerCore_DelayedToString;
}

@end


#line 21
void FreemarkerCore_DelayedToString_initWithId_(FreemarkerCore_DelayedToString *self, id object) {
  (void) FreemarkerCore_DelayedConversionToString_initWithId_(self, object);
}


#line 21
FreemarkerCore_DelayedToString *new_FreemarkerCore_DelayedToString_initWithId_(id object) {
  FreemarkerCore_DelayedToString *self = [FreemarkerCore_DelayedToString alloc];
  FreemarkerCore_DelayedToString_initWithId_(self, object);
  return self;
}


#line 25
void FreemarkerCore_DelayedToString_initWithInt_(FreemarkerCore_DelayedToString *self, jint object) {
  (void) FreemarkerCore_DelayedConversionToString_initWithId_(self, new_JavaLangInteger_initWithInt_(object));
}


#line 25
FreemarkerCore_DelayedToString *new_FreemarkerCore_DelayedToString_initWithInt_(jint object) {
  FreemarkerCore_DelayedToString *self = [FreemarkerCore_DelayedToString alloc];
  FreemarkerCore_DelayedToString_initWithInt_(self, object);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(FreemarkerCore_DelayedToString)
