//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/template/utility/Constants.java
//


#include "Constants.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "SimpleNumber.h"
#include "TemplateBooleanModel.h"
#include "TemplateCollectionModel.h"
#include "TemplateHashModelEx.h"
#include "TemplateModel.h"
#include "TemplateModelException.h"
#include "TemplateModelIterator.h"
#include "TemplateNumberModel.h"
#include "TemplateScalarModel.h"
#include "TemplateSequenceModel.h"
#include "java/io/Serializable.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/template/utility/Constants.java"

@interface FreemarkerTemplateUtilityConstants_EmptyIteratorModel : NSObject < FreemarkerTemplateTemplateModelIterator, JavaIoSerializable >

- (id<FreemarkerTemplateTemplateModel>)next;

- (jboolean)hasNext;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(FreemarkerTemplateUtilityConstants_EmptyIteratorModel)

__attribute__((unused)) static void FreemarkerTemplateUtilityConstants_EmptyIteratorModel_init(FreemarkerTemplateUtilityConstants_EmptyIteratorModel *self);

__attribute__((unused)) static FreemarkerTemplateUtilityConstants_EmptyIteratorModel *new_FreemarkerTemplateUtilityConstants_EmptyIteratorModel_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerTemplateUtilityConstants_EmptyIteratorModel)

@interface FreemarkerTemplateUtilityConstants_EmptyCollectionModel : NSObject < FreemarkerTemplateTemplateCollectionModel, JavaIoSerializable >

- (id<FreemarkerTemplateTemplateModelIterator>)iterator;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(FreemarkerTemplateUtilityConstants_EmptyCollectionModel)

__attribute__((unused)) static void FreemarkerTemplateUtilityConstants_EmptyCollectionModel_init(FreemarkerTemplateUtilityConstants_EmptyCollectionModel *self);

__attribute__((unused)) static FreemarkerTemplateUtilityConstants_EmptyCollectionModel *new_FreemarkerTemplateUtilityConstants_EmptyCollectionModel_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerTemplateUtilityConstants_EmptyCollectionModel)

@interface FreemarkerTemplateUtilityConstants_EmptySequenceModel : NSObject < FreemarkerTemplateTemplateSequenceModel, JavaIoSerializable >

- (id<FreemarkerTemplateTemplateModel>)getWithInt:(jint)index;

- (jint)size;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(FreemarkerTemplateUtilityConstants_EmptySequenceModel)

__attribute__((unused)) static void FreemarkerTemplateUtilityConstants_EmptySequenceModel_init(FreemarkerTemplateUtilityConstants_EmptySequenceModel *self);

__attribute__((unused)) static FreemarkerTemplateUtilityConstants_EmptySequenceModel *new_FreemarkerTemplateUtilityConstants_EmptySequenceModel_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerTemplateUtilityConstants_EmptySequenceModel)

@interface FreemarkerTemplateUtilityConstants_EmptyHashModel : NSObject < FreemarkerTemplateTemplateHashModelEx, JavaIoSerializable >

- (jint)size;

- (id<FreemarkerTemplateTemplateCollectionModel>)keys;

- (id<FreemarkerTemplateTemplateCollectionModel>)values;

- (id<FreemarkerTemplateTemplateModel>)getWithNSString:(NSString *)key;

- (jboolean)isEmpty;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(FreemarkerTemplateUtilityConstants_EmptyHashModel)

__attribute__((unused)) static void FreemarkerTemplateUtilityConstants_EmptyHashModel_init(FreemarkerTemplateUtilityConstants_EmptyHashModel *self);

__attribute__((unused)) static FreemarkerTemplateUtilityConstants_EmptyHashModel *new_FreemarkerTemplateUtilityConstants_EmptyHashModel_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerTemplateUtilityConstants_EmptyHashModel)

J2OBJC_INITIALIZED_DEFN(FreemarkerTemplateUtilityConstants)

id<FreemarkerTemplateTemplateBooleanModel> FreemarkerTemplateUtilityConstants_TRUE__;
id<FreemarkerTemplateTemplateBooleanModel> FreemarkerTemplateUtilityConstants_FALSE__;
id<FreemarkerTemplateTemplateScalarModel> FreemarkerTemplateUtilityConstants_EMPTY_STRING_;
id<FreemarkerTemplateTemplateNumberModel> FreemarkerTemplateUtilityConstants_ZERO_;
id<FreemarkerTemplateTemplateNumberModel> FreemarkerTemplateUtilityConstants_ONE_;
id<FreemarkerTemplateTemplateNumberModel> FreemarkerTemplateUtilityConstants_MINUS_ONE_;
id<FreemarkerTemplateTemplateModelIterator> FreemarkerTemplateUtilityConstants_EMPTY_ITERATOR_;
id<FreemarkerTemplateTemplateCollectionModel> FreemarkerTemplateUtilityConstants_EMPTY_COLLECTION_;
id<FreemarkerTemplateTemplateSequenceModel> FreemarkerTemplateUtilityConstants_EMPTY_SEQUENCE_;
id<FreemarkerTemplateTemplateHashModelEx> FreemarkerTemplateUtilityConstants_EMPTY_HASH_;


#line 41
@implementation FreemarkerTemplateUtilityConstants

- (instancetype)init {
  FreemarkerTemplateUtilityConstants_init(self);
  return self;
}

+ (void)initialize {
  if (self == [FreemarkerTemplateUtilityConstants class]) {
    FreemarkerTemplateUtilityConstants_TRUE__ = FreemarkerTemplateTemplateBooleanModel_get_TRUE__();
    FreemarkerTemplateUtilityConstants_FALSE__ = FreemarkerTemplateTemplateBooleanModel_get_FALSE__();
    FreemarkerTemplateUtilityConstants_EMPTY_STRING_ = (id<FreemarkerTemplateTemplateScalarModel>) check_protocol_cast(FreemarkerTemplateTemplateScalarModel_get_EMPTY_STRING_(), @protocol(FreemarkerTemplateTemplateScalarModel));
    FreemarkerTemplateUtilityConstants_ZERO_ = new_FreemarkerTemplateSimpleNumber_initWithInt_(
#line 49
    0);
    FreemarkerTemplateUtilityConstants_ONE_ = new_FreemarkerTemplateSimpleNumber_initWithInt_(
#line 51
    1);
    FreemarkerTemplateUtilityConstants_MINUS_ONE_ = new_FreemarkerTemplateSimpleNumber_initWithInt_(
#line 53
    -1);
    FreemarkerTemplateUtilityConstants_EMPTY_ITERATOR_ = new_FreemarkerTemplateUtilityConstants_EmptyIteratorModel_init();
    FreemarkerTemplateUtilityConstants_EMPTY_COLLECTION_ = new_FreemarkerTemplateUtilityConstants_EmptyCollectionModel_init();
    FreemarkerTemplateUtilityConstants_EMPTY_SEQUENCE_ = new_FreemarkerTemplateUtilityConstants_EmptySequenceModel_init();
    FreemarkerTemplateUtilityConstants_EMPTY_HASH_ = new_FreemarkerTemplateUtilityConstants_EmptyHashModel_init();
    J2OBJC_SET_INITIALIZED(FreemarkerTemplateUtilityConstants)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "TRUE__", "TRUE", 0x19, "Lfreemarker.template.TemplateBooleanModel;", &FreemarkerTemplateUtilityConstants_TRUE__, NULL,  },
    { "FALSE__", "FALSE", 0x19, "Lfreemarker.template.TemplateBooleanModel;", &FreemarkerTemplateUtilityConstants_FALSE__, NULL,  },
    { "EMPTY_STRING_", NULL, 0x19, "Lfreemarker.template.TemplateScalarModel;", &FreemarkerTemplateUtilityConstants_EMPTY_STRING_, NULL,  },
    { "ZERO_", NULL, 0x19, "Lfreemarker.template.TemplateNumberModel;", &FreemarkerTemplateUtilityConstants_ZERO_, NULL,  },
    { "ONE_", NULL, 0x19, "Lfreemarker.template.TemplateNumberModel;", &FreemarkerTemplateUtilityConstants_ONE_, NULL,  },
    { "MINUS_ONE_", NULL, 0x19, "Lfreemarker.template.TemplateNumberModel;", &FreemarkerTemplateUtilityConstants_MINUS_ONE_, NULL,  },
    { "EMPTY_ITERATOR_", NULL, 0x19, "Lfreemarker.template.TemplateModelIterator;", &FreemarkerTemplateUtilityConstants_EMPTY_ITERATOR_, NULL,  },
    { "EMPTY_COLLECTION_", NULL, 0x19, "Lfreemarker.template.TemplateCollectionModel;", &FreemarkerTemplateUtilityConstants_EMPTY_COLLECTION_, NULL,  },
    { "EMPTY_SEQUENCE_", NULL, 0x19, "Lfreemarker.template.TemplateSequenceModel;", &FreemarkerTemplateUtilityConstants_EMPTY_SEQUENCE_, NULL,  },
    { "EMPTY_HASH_", NULL, 0x19, "Lfreemarker.template.TemplateHashModelEx;", &FreemarkerTemplateUtilityConstants_EMPTY_HASH_, NULL,  },
  };
  static const char *inner_classes[] = {"Lfreemarker.template.utility.Constants$EmptyIteratorModel;", "Lfreemarker.template.utility.Constants$EmptyCollectionModel;", "Lfreemarker.template.utility.Constants$EmptySequenceModel;", "Lfreemarker.template.utility.Constants$EmptyHashModel;"};
  static const J2ObjcClassInfo _FreemarkerTemplateUtilityConstants = { 2, "Constants", "freemarker.template.utility", NULL, 0x1, 1, methods, 10, fields, 0, NULL, 4, inner_classes, NULL, NULL };
  return &_FreemarkerTemplateUtilityConstants;
}

@end

void FreemarkerTemplateUtilityConstants_init(FreemarkerTemplateUtilityConstants *self) {
  (void) NSObject_init(self);
}

FreemarkerTemplateUtilityConstants *new_FreemarkerTemplateUtilityConstants_init() {
  FreemarkerTemplateUtilityConstants *self = [FreemarkerTemplateUtilityConstants alloc];
  FreemarkerTemplateUtilityConstants_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(FreemarkerTemplateUtilityConstants)


#line 57
@implementation FreemarkerTemplateUtilityConstants_EmptyIteratorModel

- (id<FreemarkerTemplateTemplateModel>)next {
  @throw new_FreemarkerTemplateTemplateModelException_initWithNSString_(@"The collection has no more elements.");
}

- (jboolean)hasNext {
  return NO;
}

- (instancetype)init {
  FreemarkerTemplateUtilityConstants_EmptyIteratorModel_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "next", NULL, "Lfreemarker.template.TemplateModel;", 0x1, "Lfreemarker.template.TemplateModelException;", NULL },
    { "hasNext", NULL, "Z", 0x1, "Lfreemarker.template.TemplateModelException;", NULL },
    { "init", NULL, NULL, 0x2, NULL, NULL },
  };
  static const J2ObjcClassInfo _FreemarkerTemplateUtilityConstants_EmptyIteratorModel = { 2, "EmptyIteratorModel", "freemarker.template.utility", "Constants", 0xa, 3, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_FreemarkerTemplateUtilityConstants_EmptyIteratorModel;
}

@end

void FreemarkerTemplateUtilityConstants_EmptyIteratorModel_init(FreemarkerTemplateUtilityConstants_EmptyIteratorModel *self) {
  (void) NSObject_init(self);
}

FreemarkerTemplateUtilityConstants_EmptyIteratorModel *new_FreemarkerTemplateUtilityConstants_EmptyIteratorModel_init() {
  FreemarkerTemplateUtilityConstants_EmptyIteratorModel *self = [FreemarkerTemplateUtilityConstants_EmptyIteratorModel alloc];
  FreemarkerTemplateUtilityConstants_EmptyIteratorModel_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(FreemarkerTemplateUtilityConstants_EmptyIteratorModel)


#line 71
@implementation FreemarkerTemplateUtilityConstants_EmptyCollectionModel

- (id<FreemarkerTemplateTemplateModelIterator>)iterator {
  return FreemarkerTemplateUtilityConstants_get_EMPTY_ITERATOR_();
}

- (instancetype)init {
  FreemarkerTemplateUtilityConstants_EmptyCollectionModel_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "iterator", NULL, "Lfreemarker.template.TemplateModelIterator;", 0x1, "Lfreemarker.template.TemplateModelException;", NULL },
    { "init", NULL, NULL, 0x2, NULL, NULL },
  };
  static const J2ObjcClassInfo _FreemarkerTemplateUtilityConstants_EmptyCollectionModel = { 2, "EmptyCollectionModel", "freemarker.template.utility", "Constants", 0xa, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_FreemarkerTemplateUtilityConstants_EmptyCollectionModel;
}

@end

void FreemarkerTemplateUtilityConstants_EmptyCollectionModel_init(FreemarkerTemplateUtilityConstants_EmptyCollectionModel *self) {
  (void) NSObject_init(self);
}

FreemarkerTemplateUtilityConstants_EmptyCollectionModel *new_FreemarkerTemplateUtilityConstants_EmptyCollectionModel_init() {
  FreemarkerTemplateUtilityConstants_EmptyCollectionModel *self = [FreemarkerTemplateUtilityConstants_EmptyCollectionModel alloc];
  FreemarkerTemplateUtilityConstants_EmptyCollectionModel_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(FreemarkerTemplateUtilityConstants_EmptyCollectionModel)


#line 81
@implementation FreemarkerTemplateUtilityConstants_EmptySequenceModel

- (id<FreemarkerTemplateTemplateModel>)getWithInt:(jint)index {
  return nil;
}

- (jint)size {
  return 0;
}

- (instancetype)init {
  FreemarkerTemplateUtilityConstants_EmptySequenceModel_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getWithInt:", "get", "Lfreemarker.template.TemplateModel;", 0x1, "Lfreemarker.template.TemplateModelException;", NULL },
    { "size", NULL, "I", 0x1, "Lfreemarker.template.TemplateModelException;", NULL },
    { "init", NULL, NULL, 0x2, NULL, NULL },
  };
  static const J2ObjcClassInfo _FreemarkerTemplateUtilityConstants_EmptySequenceModel = { 2, "EmptySequenceModel", "freemarker.template.utility", "Constants", 0xa, 3, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_FreemarkerTemplateUtilityConstants_EmptySequenceModel;
}

@end

void FreemarkerTemplateUtilityConstants_EmptySequenceModel_init(FreemarkerTemplateUtilityConstants_EmptySequenceModel *self) {
  (void) NSObject_init(self);
}

FreemarkerTemplateUtilityConstants_EmptySequenceModel *new_FreemarkerTemplateUtilityConstants_EmptySequenceModel_init() {
  FreemarkerTemplateUtilityConstants_EmptySequenceModel *self = [FreemarkerTemplateUtilityConstants_EmptySequenceModel alloc];
  FreemarkerTemplateUtilityConstants_EmptySequenceModel_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(FreemarkerTemplateUtilityConstants_EmptySequenceModel)


#line 95
@implementation FreemarkerTemplateUtilityConstants_EmptyHashModel

- (jint)size {
  return 0;
}

- (id<FreemarkerTemplateTemplateCollectionModel>)keys {
  return FreemarkerTemplateUtilityConstants_get_EMPTY_COLLECTION_();
}

- (id<FreemarkerTemplateTemplateCollectionModel>)values {
  return FreemarkerTemplateUtilityConstants_get_EMPTY_COLLECTION_();
}

- (id<FreemarkerTemplateTemplateModel>)getWithNSString:(NSString *)key {
  return nil;
}

- (jboolean)isEmpty {
  return YES;
}

- (instancetype)init {
  FreemarkerTemplateUtilityConstants_EmptyHashModel_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "size", NULL, "I", 0x1, "Lfreemarker.template.TemplateModelException;", NULL },
    { "keys", NULL, "Lfreemarker.template.TemplateCollectionModel;", 0x1, "Lfreemarker.template.TemplateModelException;", NULL },
    { "values", NULL, "Lfreemarker.template.TemplateCollectionModel;", 0x1, "Lfreemarker.template.TemplateModelException;", NULL },
    { "getWithNSString:", "get", "Lfreemarker.template.TemplateModel;", 0x1, "Lfreemarker.template.TemplateModelException;", NULL },
    { "isEmpty", NULL, "Z", 0x1, "Lfreemarker.template.TemplateModelException;", NULL },
    { "init", NULL, NULL, 0x2, NULL, NULL },
  };
  static const J2ObjcClassInfo _FreemarkerTemplateUtilityConstants_EmptyHashModel = { 2, "EmptyHashModel", "freemarker.template.utility", "Constants", 0xa, 6, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_FreemarkerTemplateUtilityConstants_EmptyHashModel;
}

@end

void FreemarkerTemplateUtilityConstants_EmptyHashModel_init(FreemarkerTemplateUtilityConstants_EmptyHashModel *self) {
  (void) NSObject_init(self);
}

FreemarkerTemplateUtilityConstants_EmptyHashModel *new_FreemarkerTemplateUtilityConstants_EmptyHashModel_init() {
  FreemarkerTemplateUtilityConstants_EmptyHashModel *self = [FreemarkerTemplateUtilityConstants_EmptyHashModel alloc];
  FreemarkerTemplateUtilityConstants_EmptyHashModel_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(FreemarkerTemplateUtilityConstants_EmptyHashModel)
