//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/template/DefaultObjectWrapperConfiguration.java
//

#ifndef _FreemarkerTemplateDefaultObjectWrapperConfiguration_H_
#define _FreemarkerTemplateDefaultObjectWrapperConfiguration_H_

#include "BeansWrapperConfiguration.h"
#include "J2ObjC_header.h"

@class FreemarkerTemplateVersion;

/**
 @brief Holds DefaultObjectWrapper configuration settings and defines their defaults.
 You will not use this abstract class directly, but concrete subclasses like DefaultObjectWrapperBuilder . Unless, you are developing a builder for a custom DefaultObjectWrapper subclass. In that case, note that overriding the #equals and #hashCode is important, as these object are used as ObjectWrapper singleton lookup keys.
 @since 2.3.22
 */
@interface FreemarkerTemplateDefaultObjectWrapperConfiguration : FreemarkerExtBeansBeansWrapperConfiguration

#pragma mark Public

- (jboolean)isEqual:(id)that;

/**
 @brief See DefaultObjectWrapper#getForceLegacyNonListCollections() .
 */
- (jboolean)getForceLegacyNonListCollections;

/**
 @brief See DefaultObjectWrapper#getUseAdaptersForContainers() .
 */
- (jboolean)getUseAdaptersForContainers;

- (NSUInteger)hash;

/**
 @brief See DefaultObjectWrapper#setForceLegacyNonListCollections(boolean) .
 */
- (void)setForceLegacyNonListCollectionsWithBoolean:(jboolean)legacyNonListCollectionWrapping;

/**
 @brief See DefaultObjectWrapper#setUseAdaptersForContainers(boolean) .
 */
- (void)setUseAdaptersForContainersWithBoolean:(jboolean)useAdaptersForContainers;

#pragma mark Protected

- (instancetype)initWithFreemarkerTemplateVersion:(FreemarkerTemplateVersion *)incompatibleImprovements;

@end

J2OBJC_EMPTY_STATIC_INIT(FreemarkerTemplateDefaultObjectWrapperConfiguration)

FOUNDATION_EXPORT void FreemarkerTemplateDefaultObjectWrapperConfiguration_initWithFreemarkerTemplateVersion_(FreemarkerTemplateDefaultObjectWrapperConfiguration *self, FreemarkerTemplateVersion *incompatibleImprovements);

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerTemplateDefaultObjectWrapperConfiguration)

#endif // _FreemarkerTemplateDefaultObjectWrapperConfiguration_H_
