//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/core/Dot.java
//

#ifndef _FreemarkerCoreDot_H_
#define _FreemarkerCoreDot_H_

#include "Expression.h"
#include "J2ObjC_header.h"

@class FreemarkerCoreEnvironment;
@class FreemarkerCoreParameterRole;
@protocol FreemarkerTemplateTemplateModel;

/**
 @brief The dot operator.
 Used to reference items inside a <code>TemplateHashModel</code>.
 */
@interface FreemarkerCoreDot : FreemarkerCoreExpression

#pragma mark Public

- (NSString *)getCanonicalForm;

#pragma mark Protected

- (FreemarkerCoreExpression *)deepCloneWithIdentifierReplaced_innerWithNSString:(NSString *)replacedIdentifier
                                                   withFreemarkerCoreExpression:(FreemarkerCoreExpression *)replacement
                                 withFreemarkerCoreExpression_ReplacemenetState:(FreemarkerCoreExpression_ReplacemenetState *)replacementState;

#pragma mark Package-Private

- (instancetype)initWithFreemarkerCoreExpression:(FreemarkerCoreExpression *)target
                                    withNSString:(NSString *)key;

- (id<FreemarkerTemplateTemplateModel>)_evalWithFreemarkerCoreEnvironment:(FreemarkerCoreEnvironment *)env;

- (NSString *)getNodeTypeSymbol;

- (jint)getParameterCount;

- (FreemarkerCoreParameterRole *)getParameterRoleWithInt:(jint)idx;

- (id)getParameterValueWithInt:(jint)idx;

- (NSString *)getRHO;

- (jboolean)isLiteral;

- (jboolean)onlyHasIdentifiers;

@end

J2OBJC_EMPTY_STATIC_INIT(FreemarkerCoreDot)

FOUNDATION_EXPORT void FreemarkerCoreDot_initWithFreemarkerCoreExpression_withNSString_(FreemarkerCoreDot *self, FreemarkerCoreExpression *target, NSString *key);

FOUNDATION_EXPORT FreemarkerCoreDot *new_FreemarkerCoreDot_initWithFreemarkerCoreExpression_withNSString_(FreemarkerCoreExpression *target, NSString *key) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerCoreDot)

#endif // _FreemarkerCoreDot_H_
