//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/core/ExistenceBuiltins.java
//

#ifndef _FreemarkerCoreExistenceBuiltins_H_
#define _FreemarkerCoreExistenceBuiltins_H_

#include "BuiltIn.h"
#include "J2ObjC_header.h"

@class FreemarkerCoreEnvironment;
@protocol FreemarkerTemplateTemplateModel;

/**
 @brief A holder for builtins that deal with null left-hand values.
 */
@interface FreemarkerCoreExistenceBuiltins : NSObject

@end

J2OBJC_EMPTY_STATIC_INIT(FreemarkerCoreExistenceBuiltins)

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerCoreExistenceBuiltins)

@interface FreemarkerCoreExistenceBuiltins_ExistenceBuiltIn : FreemarkerCoreBuiltIn

#pragma mark Protected

- (id<FreemarkerTemplateTemplateModel>)evalMaybeNonexistentTargetWithFreemarkerCoreEnvironment:(FreemarkerCoreEnvironment *)env;

@end

J2OBJC_EMPTY_STATIC_INIT(FreemarkerCoreExistenceBuiltins_ExistenceBuiltIn)

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerCoreExistenceBuiltins_ExistenceBuiltIn)

@interface FreemarkerCoreExistenceBuiltins_defaultBI : FreemarkerCoreExistenceBuiltins_ExistenceBuiltIn

#pragma mark Package-Private

- (instancetype)init;

- (id<FreemarkerTemplateTemplateModel>)_evalWithFreemarkerCoreEnvironment:(FreemarkerCoreEnvironment *)env;

@end

J2OBJC_STATIC_INIT(FreemarkerCoreExistenceBuiltins_defaultBI)

FOUNDATION_EXPORT void FreemarkerCoreExistenceBuiltins_defaultBI_init(FreemarkerCoreExistenceBuiltins_defaultBI *self);

FOUNDATION_EXPORT FreemarkerCoreExistenceBuiltins_defaultBI *new_FreemarkerCoreExistenceBuiltins_defaultBI_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerCoreExistenceBuiltins_defaultBI)

@interface FreemarkerCoreExistenceBuiltins_existsBI : FreemarkerCoreExistenceBuiltins_ExistenceBuiltIn

#pragma mark Package-Private

- (instancetype)init;

- (id<FreemarkerTemplateTemplateModel>)_evalWithFreemarkerCoreEnvironment:(FreemarkerCoreEnvironment *)env;

- (jboolean)evalToBooleanWithFreemarkerCoreEnvironment:(FreemarkerCoreEnvironment *)env;

@end

J2OBJC_EMPTY_STATIC_INIT(FreemarkerCoreExistenceBuiltins_existsBI)

FOUNDATION_EXPORT void FreemarkerCoreExistenceBuiltins_existsBI_init(FreemarkerCoreExistenceBuiltins_existsBI *self);

FOUNDATION_EXPORT FreemarkerCoreExistenceBuiltins_existsBI *new_FreemarkerCoreExistenceBuiltins_existsBI_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerCoreExistenceBuiltins_existsBI)

@interface FreemarkerCoreExistenceBuiltins_has_contentBI : FreemarkerCoreExistenceBuiltins_ExistenceBuiltIn

#pragma mark Package-Private

- (instancetype)init;

- (id<FreemarkerTemplateTemplateModel>)_evalWithFreemarkerCoreEnvironment:(FreemarkerCoreEnvironment *)env;

- (jboolean)evalToBooleanWithFreemarkerCoreEnvironment:(FreemarkerCoreEnvironment *)env;

@end

J2OBJC_EMPTY_STATIC_INIT(FreemarkerCoreExistenceBuiltins_has_contentBI)

FOUNDATION_EXPORT void FreemarkerCoreExistenceBuiltins_has_contentBI_init(FreemarkerCoreExistenceBuiltins_has_contentBI *self);

FOUNDATION_EXPORT FreemarkerCoreExistenceBuiltins_has_contentBI *new_FreemarkerCoreExistenceBuiltins_has_contentBI_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerCoreExistenceBuiltins_has_contentBI)

@interface FreemarkerCoreExistenceBuiltins_if_existsBI : FreemarkerCoreExistenceBuiltins_ExistenceBuiltIn

#pragma mark Package-Private

- (instancetype)init;

- (id<FreemarkerTemplateTemplateModel>)_evalWithFreemarkerCoreEnvironment:(FreemarkerCoreEnvironment *)env;

@end

J2OBJC_EMPTY_STATIC_INIT(FreemarkerCoreExistenceBuiltins_if_existsBI)

FOUNDATION_EXPORT void FreemarkerCoreExistenceBuiltins_if_existsBI_init(FreemarkerCoreExistenceBuiltins_if_existsBI *self);

FOUNDATION_EXPORT FreemarkerCoreExistenceBuiltins_if_existsBI *new_FreemarkerCoreExistenceBuiltins_if_existsBI_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerCoreExistenceBuiltins_if_existsBI)

#endif // _FreemarkerCoreExistenceBuiltins_H_
