//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/core/FMParserTokenManager.java
//

#ifndef _FreemarkerCoreFMParserTokenManager_H_
#define _FreemarkerCoreFMParserTokenManager_H_

#include "FMParserConstants.h"
#include "J2ObjC_header.h"

@class FreemarkerCoreFMParser;
@class FreemarkerCoreSimpleCharStream;
@class FreemarkerCoreToken;
@class FreemarkerTemplateTemplate;
@class IOSIntArray;
@class IOSLongArray;
@class IOSObjectArray;
@class JavaIoPrintStream;

/**
 @brief Token Manager.
 */
@interface FreemarkerCoreFMParserTokenManager : NSObject < FreemarkerCoreFMParserConstants > {
 @public
  /**
   @brief The noparseTag is set when we enter a block of text that the parser more or less ignores.
   These are <noparse> and <comment>. This variable tells us what the closing tag should be, and when we hit that, we resume parsing. Note that with this scheme, <comment> and <noparse> tags cannot nest recursively, but it is not clear how important that is.
   */
  NSString *noparseTag_;
  jboolean strictEscapeSyntax_, onlyTextOutput_, squBracTagSyntax_, autodetectTagSyntax_, directiveSyntaxEstablished_, inInvocation_;
  jint initialNamingConvention_;
  jint namingConvention_;
  FreemarkerCoreToken *namingConventionEstabilisher_;
  jint incompatibleImprovements_;
  /**
   @brief Debug output.
   */
  JavaIoPrintStream *debugStream_;
  jint curLexState_;
  jint defaultLexState_;
  jint jjnewStateCnt_;
  jint jjround_;
  jint jjmatchedPos_;
  jint jjmatchedKind_;
  FreemarkerCoreSimpleCharStream *input_stream_;
  jchar curChar_;
}

#pragma mark Public

/**
 @brief Constructor.
 */
- (instancetype)initWithFreemarkerCoreSimpleCharStream:(FreemarkerCoreSimpleCharStream *)stream;

/**
 @brief Constructor.
 */
- (instancetype)initWithFreemarkerCoreSimpleCharStream:(FreemarkerCoreSimpleCharStream *)stream
                                               withInt:(jint)lexState;

/**
 @brief Get the next Token.
 */
- (FreemarkerCoreToken *)getNextToken;

/**
 @brief Reinitialise parser.
 */
- (void)ReInitWithFreemarkerCoreSimpleCharStream:(FreemarkerCoreSimpleCharStream *)stream;

/**
 @brief Reinitialise parser.
 */
- (void)ReInitWithFreemarkerCoreSimpleCharStream:(FreemarkerCoreSimpleCharStream *)stream
                                         withInt:(jint)lexState;

/**
 @brief Set debug output.
 */
- (void)setDebugStreamWithJavaIoPrintStream:(JavaIoPrintStream *)ds;

/**
 @brief Switch to specified lex state.
 */
- (void)SwitchToWithInt:(jint)lexState;

#pragma mark Protected

- (FreemarkerCoreToken *)jjFillToken;

#pragma mark Package-Private

- (void)checkNamingConventionWithFreemarkerCoreToken:(FreemarkerCoreToken *)tok;

- (void)checkNamingConventionWithFreemarkerCoreToken:(FreemarkerCoreToken *)tok
                                             withInt:(jint)tokenNamingConvention;

+ (jchar)getTagNameCharAtWithFreemarkerCoreToken:(FreemarkerCoreToken *)tok
                                         withInt:(jint)charIdxInName;

- (FreemarkerTemplateTemplate *)getTemplate;

- (void)setParserWithFreemarkerCoreFMParser:(FreemarkerCoreFMParser *)parser;

- (void)SkipLexicalActionsWithFreemarkerCoreToken:(FreemarkerCoreToken *)matchedToken;

- (void)TokenLexicalActionsWithFreemarkerCoreToken:(FreemarkerCoreToken *)matchedToken;

@end

J2OBJC_STATIC_INIT(FreemarkerCoreFMParserTokenManager)

J2OBJC_FIELD_SETTER(FreemarkerCoreFMParserTokenManager, noparseTag_, NSString *)
J2OBJC_FIELD_SETTER(FreemarkerCoreFMParserTokenManager, namingConventionEstabilisher_, FreemarkerCoreToken *)
J2OBJC_FIELD_SETTER(FreemarkerCoreFMParserTokenManager, debugStream_, JavaIoPrintStream *)
J2OBJC_FIELD_SETTER(FreemarkerCoreFMParserTokenManager, input_stream_, FreemarkerCoreSimpleCharStream *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec0_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec0_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec2_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec2_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec3_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec3_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec4_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec4_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec5_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec5_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec6_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec6_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec7_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec7_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec8_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec8_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec9_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec9_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec10_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec10_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec11_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec11_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec12_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec12_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec13_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec13_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec14_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec14_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec15_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec15_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec16_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec16_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec17_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec17_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec18_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec18_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec19_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec19_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec20_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec20_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec21_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec21_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec22_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec22_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec23_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec23_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec24_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec24_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjbitVec25_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjbitVec25_, IOSLongArray *)

FOUNDATION_EXPORT IOSIntArray *FreemarkerCoreFMParserTokenManager_jjnextStates_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjnextStates_, IOSIntArray *)

FOUNDATION_EXPORT IOSObjectArray *FreemarkerCoreFMParserTokenManager_jjstrLiteralImages_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjstrLiteralImages_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *FreemarkerCoreFMParserTokenManager_lexStateNames_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, lexStateNames_, IOSObjectArray *)

FOUNDATION_EXPORT IOSIntArray *FreemarkerCoreFMParserTokenManager_jjnewLexState_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjnewLexState_, IOSIntArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjtoToken_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjtoToken_, IOSLongArray *)

FOUNDATION_EXPORT IOSLongArray *FreemarkerCoreFMParserTokenManager_jjtoSkip_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerCoreFMParserTokenManager, jjtoSkip_, IOSLongArray *)

FOUNDATION_EXPORT jchar FreemarkerCoreFMParserTokenManager_getTagNameCharAtWithFreemarkerCoreToken_withInt_(FreemarkerCoreToken *tok, jint charIdxInName);

FOUNDATION_EXPORT void FreemarkerCoreFMParserTokenManager_initWithFreemarkerCoreSimpleCharStream_(FreemarkerCoreFMParserTokenManager *self, FreemarkerCoreSimpleCharStream *stream);

FOUNDATION_EXPORT FreemarkerCoreFMParserTokenManager *new_FreemarkerCoreFMParserTokenManager_initWithFreemarkerCoreSimpleCharStream_(FreemarkerCoreSimpleCharStream *stream) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void FreemarkerCoreFMParserTokenManager_initWithFreemarkerCoreSimpleCharStream_withInt_(FreemarkerCoreFMParserTokenManager *self, FreemarkerCoreSimpleCharStream *stream, jint lexState);

FOUNDATION_EXPORT FreemarkerCoreFMParserTokenManager *new_FreemarkerCoreFMParserTokenManager_initWithFreemarkerCoreSimpleCharStream_withInt_(FreemarkerCoreSimpleCharStream *stream, jint lexState) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerCoreFMParserTokenManager)

#endif // _FreemarkerCoreFMParserTokenManager_H_
