//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/ext/beans/ReflectionCallableMemberDescriptor.java
//

#ifndef _FreemarkerExtBeansReflectionCallableMemberDescriptor_H_
#define _FreemarkerExtBeansReflectionCallableMemberDescriptor_H_

#include "CallableMemberDescriptor.h"
#include "J2ObjC_header.h"

@class FreemarkerExtBeansBeansWrapper;
@class IOSObjectArray;
@class JavaLangReflectConstructor;
@class JavaLangReflectMethod;
@protocol FreemarkerTemplateTemplateModel;

/**
 @brief The most commonly used CallableMemberDescriptor implementation.
 */
@interface FreemarkerExtBeansReflectionCallableMemberDescriptor : FreemarkerExtBeansCallableMemberDescriptor {
 @public
  /**
   @brief Don't modify this array!
   */
  IOSObjectArray *paramTypes_;
}

#pragma mark Package-Private

- (instancetype)initWithJavaLangReflectConstructor:(JavaLangReflectConstructor *)member
                                 withIOSClassArray:(IOSObjectArray *)paramTypes;

- (instancetype)initWithJavaLangReflectMethod:(JavaLangReflectMethod *)member
                            withIOSClassArray:(IOSObjectArray *)paramTypes;

- (NSString *)getDeclaration;

- (NSString *)getName;

- (IOSObjectArray *)getParamTypes;

- (id)invokeConstructorWithFreemarkerExtBeansBeansWrapper:(FreemarkerExtBeansBeansWrapper *)bw
                                        withNSObjectArray:(IOSObjectArray *)args;

- (id<FreemarkerTemplateTemplateModel>)invokeMethodWithFreemarkerExtBeansBeansWrapper:(FreemarkerExtBeansBeansWrapper *)bw
                                                                               withId:(id)obj
                                                                    withNSObjectArray:(IOSObjectArray *)args;

- (jboolean)isConstructor;

- (jboolean)isStatic;

- (jboolean)isVarargs;

@end

J2OBJC_EMPTY_STATIC_INIT(FreemarkerExtBeansReflectionCallableMemberDescriptor)

J2OBJC_FIELD_SETTER(FreemarkerExtBeansReflectionCallableMemberDescriptor, paramTypes_, IOSObjectArray *)

FOUNDATION_EXPORT void FreemarkerExtBeansReflectionCallableMemberDescriptor_initWithJavaLangReflectMethod_withIOSClassArray_(FreemarkerExtBeansReflectionCallableMemberDescriptor *self, JavaLangReflectMethod *member, IOSObjectArray *paramTypes);

FOUNDATION_EXPORT FreemarkerExtBeansReflectionCallableMemberDescriptor *new_FreemarkerExtBeansReflectionCallableMemberDescriptor_initWithJavaLangReflectMethod_withIOSClassArray_(JavaLangReflectMethod *member, IOSObjectArray *paramTypes) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void FreemarkerExtBeansReflectionCallableMemberDescriptor_initWithJavaLangReflectConstructor_withIOSClassArray_(FreemarkerExtBeansReflectionCallableMemberDescriptor *self, JavaLangReflectConstructor *member, IOSObjectArray *paramTypes);

FOUNDATION_EXPORT FreemarkerExtBeansReflectionCallableMemberDescriptor *new_FreemarkerExtBeansReflectionCallableMemberDescriptor_initWithJavaLangReflectConstructor_withIOSClassArray_(JavaLangReflectConstructor *member, IOSObjectArray *paramTypes) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerExtBeansReflectionCallableMemberDescriptor)

#endif // _FreemarkerExtBeansReflectionCallableMemberDescriptor_H_
