//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/template/ResourceBundleLocalizedString.java
//

#ifndef _FreemarkerTemplateResourceBundleLocalizedString_H_
#define _FreemarkerTemplateResourceBundleLocalizedString_H_

#include "J2ObjC_header.h"
#include "LocalizedString.h"

@class JavaUtilLocale;

/**
 @brief A concrete implementation of LocalizedString that gets a localized string from a java.util.ResourceBundle
 */
@interface FreemarkerTemplateResourceBundleLocalizedString : FreemarkerTemplateLocalizedString

#pragma mark Public

/**
 @param resourceBundleLookupKey The lookup key for the resource bundle
 @param resourceKey the specific resource (assumed to be a string) to fish out of the resource bundle
 */
- (instancetype)initWithNSString:(NSString *)resourceBundleLookupKey
                    withNSString:(NSString *)resourceKey;

- (NSString *)getLocalizedStringWithJavaUtilLocale:(JavaUtilLocale *)locale;

@end

J2OBJC_EMPTY_STATIC_INIT(FreemarkerTemplateResourceBundleLocalizedString)

FOUNDATION_EXPORT void FreemarkerTemplateResourceBundleLocalizedString_initWithNSString_withNSString_(FreemarkerTemplateResourceBundleLocalizedString *self, NSString *resourceBundleLookupKey, NSString *resourceKey);

FOUNDATION_EXPORT FreemarkerTemplateResourceBundleLocalizedString *new_FreemarkerTemplateResourceBundleLocalizedString_initWithNSString_withNSString_(NSString *resourceBundleLookupKey, NSString *resourceKey) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerTemplateResourceBundleLocalizedString)

#endif // _FreemarkerTemplateResourceBundleLocalizedString_H_
