//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/template/SerializableTemplateBooleanModel.java
//

#ifndef _FreemarkerTemplateSerializableTemplateBooleanModel_H_
#define _FreemarkerTemplateSerializableTemplateBooleanModel_H_

#include "J2ObjC_header.h"
#include "TemplateBooleanModel.h"
#include "java/io/Serializable.h"

@protocol FreemarkerTemplateSerializableTemplateBooleanModel < FreemarkerTemplateTemplateBooleanModel, JavaIoSerializable, NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(FreemarkerTemplateSerializableTemplateBooleanModel)

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerTemplateSerializableTemplateBooleanModel)

#endif // _FreemarkerTemplateSerializableTemplateBooleanModel_H_
