//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/ext/beans/SingletonCustomizer.java
//


#include "J2ObjC_source.h"
#include "SingletonCustomizer.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/ext/beans/SingletonCustomizer.java"

@interface FreemarkerExtBeansSingletonCustomizer : NSObject
@end


#line 46
@implementation FreemarkerExtBeansSingletonCustomizer

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _FreemarkerExtBeansSingletonCustomizer = { 2, "SingletonCustomizer", "freemarker.ext.beans", NULL, 0x609, 0, NULL, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_FreemarkerExtBeansSingletonCustomizer;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(FreemarkerExtBeansSingletonCustomizer)
