//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/core/StopException.java
//

#ifndef _FreemarkerCoreStopException_H_
#define _FreemarkerCoreStopException_H_

#include "J2ObjC_header.h"
#include "TemplateException.h"

@class FreemarkerCoreEnvironment;
@class JavaIoPrintStream;
@class JavaIoPrintWriter;

/**
 @brief This exception is thrown when a <tt>#stop</tt> directive is encountered.
 */
@interface FreemarkerCoreStopException : FreemarkerTemplateTemplateException

#pragma mark Public

- (void)printStackTraceWithJavaIoPrintStream:(JavaIoPrintStream *)ps;

- (void)printStackTraceWithJavaIoPrintWriter:(JavaIoPrintWriter *)pw;

#pragma mark Package-Private

- (instancetype)initWithFreemarkerCoreEnvironment:(FreemarkerCoreEnvironment *)env;

- (instancetype)initWithFreemarkerCoreEnvironment:(FreemarkerCoreEnvironment *)env
                                     withNSString:(NSString *)s;

@end

J2OBJC_EMPTY_STATIC_INIT(FreemarkerCoreStopException)

FOUNDATION_EXPORT void FreemarkerCoreStopException_initWithFreemarkerCoreEnvironment_(FreemarkerCoreStopException *self, FreemarkerCoreEnvironment *env);

FOUNDATION_EXPORT FreemarkerCoreStopException *new_FreemarkerCoreStopException_initWithFreemarkerCoreEnvironment_(FreemarkerCoreEnvironment *env) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void FreemarkerCoreStopException_initWithFreemarkerCoreEnvironment_withNSString_(FreemarkerCoreStopException *self, FreemarkerCoreEnvironment *env, NSString *s);

FOUNDATION_EXPORT FreemarkerCoreStopException *new_FreemarkerCoreStopException_initWithFreemarkerCoreEnvironment_withNSString_(FreemarkerCoreEnvironment *env, NSString *s) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerCoreStopException)

#endif // _FreemarkerCoreStopException_H_
