//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/template/TemplateModelIterator.java
//


#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "TemplateModel.h"
#include "TemplateModelException.h"
#include "TemplateModelIterator.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/template/TemplateModelIterator.java"

@interface FreemarkerTemplateTemplateModelIterator : NSObject
@end


#line 23
@implementation FreemarkerTemplateTemplateModelIterator

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "next", NULL, "Lfreemarker.template.TemplateModel;", 0x401, "Lfreemarker.template.TemplateModelException;", NULL },
    { "hasNext", NULL, "Z", 0x401, "Lfreemarker.template.TemplateModelException;", NULL },
  };
  static const J2ObjcClassInfo _FreemarkerTemplateTemplateModelIterator = { 2, "TemplateModelIterator", "freemarker.template", NULL, 0x609, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_FreemarkerTemplateTemplateModelIterator;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(FreemarkerTemplateTemplateModelIterator)
