//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/template/TemplateDateModel.java
//

#ifndef _FreemarkerTemplateTemplateDateModel_H_
#define _FreemarkerTemplateTemplateDateModel_H_

#include "J2ObjC_header.h"
#include "TemplateModel.h"

@class JavaUtilDate;
@protocol JavaUtilList;

#define FreemarkerTemplateTemplateDateModel_UNKNOWN 0
#define FreemarkerTemplateTemplateDateModel_TIME 1
#define FreemarkerTemplateTemplateDateModel_DATE 2
#define FreemarkerTemplateTemplateDateModel_DATETIME 3

/**
 @brief "date", "time" and "date-time" template language data types: corresponds to java.util.Date .
 Contrary to Java, FreeMarker distinguishes date (no time part), time and date-time values.
 */
@protocol FreemarkerTemplateTemplateDateModel < FreemarkerTemplateTemplateModel, NSObject, JavaObject >

/**
 @brief Returns the date value.
 The return value must not be <code>null</code> .
 */
- (JavaUtilDate *)getAsDate;

/**
 @brief Returns the type of the date.
 It can be any of #TIME , #DATE , or #DATETIME .
 */
- (jint)getDateType;

@end

@interface FreemarkerTemplateTemplateDateModel : NSObject
@end

J2OBJC_STATIC_INIT(FreemarkerTemplateTemplateDateModel)

J2OBJC_STATIC_FIELD_GETTER(FreemarkerTemplateTemplateDateModel, UNKNOWN, jint)

J2OBJC_STATIC_FIELD_GETTER(FreemarkerTemplateTemplateDateModel, TIME, jint)

J2OBJC_STATIC_FIELD_GETTER(FreemarkerTemplateTemplateDateModel, DATE, jint)

J2OBJC_STATIC_FIELD_GETTER(FreemarkerTemplateTemplateDateModel, DATETIME, jint)

FOUNDATION_EXPORT id<JavaUtilList> FreemarkerTemplateTemplateDateModel_TYPE_NAMES_;
J2OBJC_STATIC_FIELD_GETTER(FreemarkerTemplateTemplateDateModel, TYPE_NAMES_, id<JavaUtilList>)

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerTemplateTemplateDateModel)

#endif // _FreemarkerTemplateTemplateDateModel_H_
