//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/template/TemplateHashModel.java
//

#ifndef _FreemarkerTemplateTemplateHashModel_H_
#define _FreemarkerTemplateTemplateHashModel_H_

#include "J2ObjC_header.h"
#include "TemplateModel.h"

/**
 @brief "hash" template language data type: an object that contains other objects accessible through string keys (sub-variable names).
 <p>In templates they are used like <code>myHash.myKey</code> or <code>myHash[myDynamicKey]</code> .
 */
@protocol FreemarkerTemplateTemplateHashModel < FreemarkerTemplateTemplateModel, NSObject, JavaObject >

/**
 @brief Gets a <tt>TemplateModel</tt> from the hash.
 @param key the name by which the <tt>TemplateModel</tt> is identified in the template.
 @return the <tt>TemplateModel</tt> referred to by the key, or null if not found.
 */
- (id<FreemarkerTemplateTemplateModel>)getWithNSString:(NSString *)key;

- (jboolean)isEmpty;

@end

J2OBJC_EMPTY_STATIC_INIT(FreemarkerTemplateTemplateHashModel)

J2OBJC_TYPE_LITERAL_HEADER(FreemarkerTemplateTemplateHashModel)

#endif // _FreemarkerTemplateTemplateHashModel_H_
