//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/cache/TemplateLookupContext.java
//


#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "TemplateLookupContext.h"
#include "TemplateLookupResult.h"
#include "java/io/IOException.h"
#include "java/util/Locale.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/cache/TemplateLookupContext.java"

@interface FreemarkerCacheTemplateLookupContext () {
 @public
  NSString *templateName_;
  JavaUtilLocale *templateLocale_;
  id customLookupCondition_;
}

@end

J2OBJC_FIELD_SETTER(FreemarkerCacheTemplateLookupContext, templateName_, NSString *)
J2OBJC_FIELD_SETTER(FreemarkerCacheTemplateLookupContext, templateLocale_, JavaUtilLocale *)
J2OBJC_FIELD_SETTER(FreemarkerCacheTemplateLookupContext, customLookupCondition_, id)


#line 30
@implementation FreemarkerCacheTemplateLookupContext


#line 48
- (FreemarkerCacheTemplateLookupResult *)lookupWithAcquisitionStrategyWithNSString:(NSString *)templateName {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}


#line 58
- (FreemarkerCacheTemplateLookupResult *)lookupWithLocalizedThenAcquisitionStrategyWithNSString:(NSString *)templateName
                                                                             withJavaUtilLocale:(JavaUtilLocale *)templateLocale {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}


#line 62
- (instancetype)initWithNSString:(NSString *)templateName
              withJavaUtilLocale:(JavaUtilLocale *)templateLocale
                          withId:(id)customLookupCondition {
  FreemarkerCacheTemplateLookupContext_initWithNSString_withJavaUtilLocale_withId_(self, templateName, templateLocale, customLookupCondition);
  return self;
}


#line 71
- (NSString *)getTemplateName {
  return templateName_;
}


#line 79
- (JavaUtilLocale *)getTemplateLocale {
  return templateLocale_;
}


#line 91
- (id)getCustomLookupCondition {
  return customLookupCondition_;
}


#line 100
- (FreemarkerCacheTemplateLookupResult *)createNegativeLookupResult {
  return FreemarkerCacheTemplateLookupResult_createNegativeResult();
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "lookupWithAcquisitionStrategyWithNSString:", "lookupWithAcquisitionStrategy", "Lfreemarker.cache.TemplateLookupResult;", 0x401, "Ljava.io.IOException;", NULL },
    { "lookupWithLocalizedThenAcquisitionStrategyWithNSString:withJavaUtilLocale:", "lookupWithLocalizedThenAcquisitionStrategy", "Lfreemarker.cache.TemplateLookupResult;", 0x401, "Ljava.io.IOException;", NULL },
    { "initWithNSString:withJavaUtilLocale:withId:", "TemplateLookupContext", NULL, 0x0, NULL, NULL },
    { "getTemplateName", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getTemplateLocale", NULL, "Ljava.util.Locale;", 0x1, NULL, NULL },
    { "getCustomLookupCondition", NULL, "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "createNegativeLookupResult", NULL, "Lfreemarker.cache.TemplateLookupResult;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "templateName_", NULL, 0x12, "Ljava.lang.String;", NULL, NULL,  },
    { "templateLocale_", NULL, 0x12, "Ljava.util.Locale;", NULL, NULL,  },
    { "customLookupCondition_", NULL, 0x12, "Ljava.lang.Object;", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _FreemarkerCacheTemplateLookupContext = { 2, "TemplateLookupContext", "freemarker.cache", NULL, 0x401, 7, methods, 3, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_FreemarkerCacheTemplateLookupContext;
}

@end


#line 62
void FreemarkerCacheTemplateLookupContext_initWithNSString_withJavaUtilLocale_withId_(FreemarkerCacheTemplateLookupContext *self, NSString *templateName, JavaUtilLocale *templateLocale, id customLookupCondition) {
  (void) NSObject_init(self);
  
#line 63
  self->templateName_ = templateName;
  self->templateLocale_ = templateLocale;
  self->customLookupCondition_ = customLookupCondition;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(FreemarkerCacheTemplateLookupContext)
