//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/core/UnknownDateTypeFormattingUnsupportedException.java
//


#include "J2ObjC_source.h"
#include "MessageUtil.h"
#include "UnformattableDateException.h"
#include "UnknownDateTypeFormattingUnsupportedException.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/freemarker/freemarker/core/UnknownDateTypeFormattingUnsupportedException.java"


#line 25
@implementation FreemarkerCoreUnknownDateTypeFormattingUnsupportedException

- (instancetype)init {
  FreemarkerCoreUnknownDateTypeFormattingUnsupportedException_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "UnknownDateTypeFormattingUnsupportedException", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _FreemarkerCoreUnknownDateTypeFormattingUnsupportedException = { 2, "UnknownDateTypeFormattingUnsupportedException", "freemarker.core", NULL, 0x10, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_FreemarkerCoreUnknownDateTypeFormattingUnsupportedException;
}

@end


#line 27
void FreemarkerCoreUnknownDateTypeFormattingUnsupportedException_init(FreemarkerCoreUnknownDateTypeFormattingUnsupportedException *self) {
  (void) FreemarkerCoreUnformattableDateException_initWithNSString_(self, FreemarkerCoreMessageUtil_get_UNKNOWN_DATE_TO_STRING_ERROR_MESSAGE_());
}


#line 27
FreemarkerCoreUnknownDateTypeFormattingUnsupportedException *new_FreemarkerCoreUnknownDateTypeFormattingUnsupportedException_init() {
  FreemarkerCoreUnknownDateTypeFormattingUnsupportedException *self = [FreemarkerCoreUnknownDateTypeFormattingUnsupportedException alloc];
  FreemarkerCoreUnknownDateTypeFormattingUnsupportedException_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(FreemarkerCoreUnknownDateTypeFormattingUnsupportedException)
