//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/annotation/MainThread.java
//

#ifndef _RepackagedAndroidAnnotationMainThread_H_
#define _RepackagedAndroidAnnotationMainThread_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

/**
 @brief Denotes that the annotated method should only be called on the main thread.
 If the annotated element is a class, then all methods in the class should be called on the main thread. <p> Example: <pre> <code>&#64;MainThread</code> public void deliverResult(D data) ... } }</pre>
 */
@protocol RepackagedAndroidAnnotationMainThread < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(RepackagedAndroidAnnotationMainThread)

J2OBJC_TYPE_LITERAL_HEADER(RepackagedAndroidAnnotationMainThread)

#endif // _RepackagedAndroidAnnotationMainThread_H_
