//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/util/MapCollections.java
//

#ifndef _RepackagedAndroidUtilMapCollections_H_
#define _RepackagedAndroidUtilMapCollections_H_

#include "J2ObjC_header.h"
#include "java/util/Collection.h"
#include "java/util/Iterator.h"
#include "java/util/Map.h"
#include "java/util/Set.h"

@class IOSObjectArray;
@class RepackagedAndroidUtilMapCollections_EntrySet;
@class RepackagedAndroidUtilMapCollections_KeySet;
@class RepackagedAndroidUtilMapCollections_ValuesCollection;

/**
 @brief Helper for writing standard Java collection interfaces to a data structure like ArrayMap .
 */
@interface RepackagedAndroidUtilMapCollections : NSObject {
 @public
  RepackagedAndroidUtilMapCollections_EntrySet *mEntrySet_;
  RepackagedAndroidUtilMapCollections_KeySet *mKeySet_;
  RepackagedAndroidUtilMapCollections_ValuesCollection *mValues_;
}

#pragma mark Public

+ (jboolean)containsAllHelperWithJavaUtilMap:(id<JavaUtilMap>)map
                      withJavaUtilCollection:(id<JavaUtilCollection>)collection;

+ (jboolean)equalsSetHelperWithJavaUtilSet:(id<JavaUtilSet>)set
                                    withId:(id)object;

- (id<JavaUtilSet>)getEntrySet;

- (id<JavaUtilSet>)getKeySet;

- (id<JavaUtilCollection>)getValues;

+ (jboolean)removeAllHelperWithJavaUtilMap:(id<JavaUtilMap>)map
                    withJavaUtilCollection:(id<JavaUtilCollection>)collection;

+ (jboolean)retainAllHelperWithJavaUtilMap:(id<JavaUtilMap>)map
                    withJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (IOSObjectArray *)toArrayHelperWithInt:(jint)offset;

- (IOSObjectArray *)toArrayHelperWithNSObjectArray:(IOSObjectArray *)array
                                           withInt:(jint)offset;

#pragma mark Protected

- (void)colClear;

- (id)colGetEntryWithInt:(jint)index
                 withInt:(jint)offset;

- (id<JavaUtilMap>)colGetMap;

- (jint)colGetSize;

- (jint)colIndexOfKeyWithId:(id)key;

- (jint)colIndexOfValueWithId:(id)key;

- (void)colPutWithId:(id)key
              withId:(id)value;

- (void)colRemoveAtWithInt:(jint)index;

- (id)colSetValueWithInt:(jint)index
                  withId:(id)value;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(RepackagedAndroidUtilMapCollections)

J2OBJC_FIELD_SETTER(RepackagedAndroidUtilMapCollections, mEntrySet_, RepackagedAndroidUtilMapCollections_EntrySet *)
J2OBJC_FIELD_SETTER(RepackagedAndroidUtilMapCollections, mKeySet_, RepackagedAndroidUtilMapCollections_KeySet *)
J2OBJC_FIELD_SETTER(RepackagedAndroidUtilMapCollections, mValues_, RepackagedAndroidUtilMapCollections_ValuesCollection *)

FOUNDATION_EXPORT jboolean RepackagedAndroidUtilMapCollections_containsAllHelperWithJavaUtilMap_withJavaUtilCollection_(id<JavaUtilMap> map, id<JavaUtilCollection> collection);

FOUNDATION_EXPORT jboolean RepackagedAndroidUtilMapCollections_removeAllHelperWithJavaUtilMap_withJavaUtilCollection_(id<JavaUtilMap> map, id<JavaUtilCollection> collection);

FOUNDATION_EXPORT jboolean RepackagedAndroidUtilMapCollections_retainAllHelperWithJavaUtilMap_withJavaUtilCollection_(id<JavaUtilMap> map, id<JavaUtilCollection> collection);

FOUNDATION_EXPORT jboolean RepackagedAndroidUtilMapCollections_equalsSetHelperWithJavaUtilSet_withId_(id<JavaUtilSet> set, id object);

FOUNDATION_EXPORT void RepackagedAndroidUtilMapCollections_init(RepackagedAndroidUtilMapCollections *self);

J2OBJC_TYPE_LITERAL_HEADER(RepackagedAndroidUtilMapCollections)

@interface RepackagedAndroidUtilMapCollections_ArrayIterator : NSObject < JavaUtilIterator > {
 @public
  jint mOffset_;
  jint mSize_;
  jint mIndex_;
  jboolean mCanRemove_;
}

#pragma mark Public

- (jboolean)hasNext;

- (id)next;

- (void)remove;

#pragma mark Package-Private

- (instancetype)initWithRepackagedAndroidUtilMapCollections:(RepackagedAndroidUtilMapCollections *)outer$
                                                    withInt:(jint)offset;

@end

J2OBJC_EMPTY_STATIC_INIT(RepackagedAndroidUtilMapCollections_ArrayIterator)

FOUNDATION_EXPORT void RepackagedAndroidUtilMapCollections_ArrayIterator_initWithRepackagedAndroidUtilMapCollections_withInt_(RepackagedAndroidUtilMapCollections_ArrayIterator *self, RepackagedAndroidUtilMapCollections *outer$, jint offset);

FOUNDATION_EXPORT RepackagedAndroidUtilMapCollections_ArrayIterator *new_RepackagedAndroidUtilMapCollections_ArrayIterator_initWithRepackagedAndroidUtilMapCollections_withInt_(RepackagedAndroidUtilMapCollections *outer$, jint offset) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(RepackagedAndroidUtilMapCollections_ArrayIterator)

@interface RepackagedAndroidUtilMapCollections_MapIterator : NSObject < JavaUtilIterator, JavaUtilMap_Entry > {
 @public
  jint mEnd_;
  jint mIndex_;
  jboolean mEntryValid_;
}

#pragma mark Public

- (jboolean)isEqual:(id)o;

- (id)getKey;

- (id)getValue;

- (NSUInteger)hash;

- (jboolean)hasNext;

- (id<JavaUtilMap_Entry>)next;

- (void)remove;

- (id)setValueWithId:(id)object;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype)initWithRepackagedAndroidUtilMapCollections:(RepackagedAndroidUtilMapCollections *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(RepackagedAndroidUtilMapCollections_MapIterator)

FOUNDATION_EXPORT void RepackagedAndroidUtilMapCollections_MapIterator_initWithRepackagedAndroidUtilMapCollections_(RepackagedAndroidUtilMapCollections_MapIterator *self, RepackagedAndroidUtilMapCollections *outer$);

FOUNDATION_EXPORT RepackagedAndroidUtilMapCollections_MapIterator *new_RepackagedAndroidUtilMapCollections_MapIterator_initWithRepackagedAndroidUtilMapCollections_(RepackagedAndroidUtilMapCollections *outer$) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(RepackagedAndroidUtilMapCollections_MapIterator)

@interface RepackagedAndroidUtilMapCollections_EntrySet : NSObject < JavaUtilSet >

#pragma mark Public

- (jboolean)addWithId:(id<JavaUtilMap_Entry>)object;

- (jboolean)addAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (void)clear;

- (jboolean)containsWithId:(id)o;

- (jboolean)containsAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (jboolean)isEqual:(id)object;

- (NSUInteger)hash;

- (jboolean)isEmpty;

- (id<JavaUtilIterator>)iterator;

- (jboolean)removeWithId:(id)object;

- (jboolean)removeAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (jboolean)retainAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (jint)size;

- (IOSObjectArray *)toArray;

- (IOSObjectArray *)toArrayWithNSObjectArray:(IOSObjectArray *)array;

#pragma mark Package-Private

- (instancetype)initWithRepackagedAndroidUtilMapCollections:(RepackagedAndroidUtilMapCollections *)outer$;


@end

J2OBJC_EMPTY_STATIC_INIT(RepackagedAndroidUtilMapCollections_EntrySet)

FOUNDATION_EXPORT void RepackagedAndroidUtilMapCollections_EntrySet_initWithRepackagedAndroidUtilMapCollections_(RepackagedAndroidUtilMapCollections_EntrySet *self, RepackagedAndroidUtilMapCollections *outer$);

FOUNDATION_EXPORT RepackagedAndroidUtilMapCollections_EntrySet *new_RepackagedAndroidUtilMapCollections_EntrySet_initWithRepackagedAndroidUtilMapCollections_(RepackagedAndroidUtilMapCollections *outer$) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(RepackagedAndroidUtilMapCollections_EntrySet)

@interface RepackagedAndroidUtilMapCollections_KeySet : NSObject < JavaUtilSet >

#pragma mark Public

- (jboolean)addWithId:(id)object;

- (jboolean)addAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (void)clear;

- (jboolean)containsWithId:(id)object;

- (jboolean)containsAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (jboolean)isEqual:(id)object;

- (NSUInteger)hash;

- (jboolean)isEmpty;

- (id<JavaUtilIterator>)iterator;

- (jboolean)removeWithId:(id)object;

- (jboolean)removeAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (jboolean)retainAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (jint)size;

- (IOSObjectArray *)toArray;

- (IOSObjectArray *)toArrayWithNSObjectArray:(IOSObjectArray *)array;

#pragma mark Package-Private

- (instancetype)initWithRepackagedAndroidUtilMapCollections:(RepackagedAndroidUtilMapCollections *)outer$;


@end

J2OBJC_EMPTY_STATIC_INIT(RepackagedAndroidUtilMapCollections_KeySet)

FOUNDATION_EXPORT void RepackagedAndroidUtilMapCollections_KeySet_initWithRepackagedAndroidUtilMapCollections_(RepackagedAndroidUtilMapCollections_KeySet *self, RepackagedAndroidUtilMapCollections *outer$);

FOUNDATION_EXPORT RepackagedAndroidUtilMapCollections_KeySet *new_RepackagedAndroidUtilMapCollections_KeySet_initWithRepackagedAndroidUtilMapCollections_(RepackagedAndroidUtilMapCollections *outer$) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(RepackagedAndroidUtilMapCollections_KeySet)

@interface RepackagedAndroidUtilMapCollections_ValuesCollection : NSObject < JavaUtilCollection >

#pragma mark Public

- (jboolean)addWithId:(id)object;

- (jboolean)addAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (void)clear;

- (jboolean)containsWithId:(id)object;

- (jboolean)containsAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (jboolean)isEmpty;

- (id<JavaUtilIterator>)iterator;

- (jboolean)removeWithId:(id)object;

- (jboolean)removeAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (jboolean)retainAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (jint)size;

- (IOSObjectArray *)toArray;

- (IOSObjectArray *)toArrayWithNSObjectArray:(IOSObjectArray *)array;

#pragma mark Package-Private

- (instancetype)initWithRepackagedAndroidUtilMapCollections:(RepackagedAndroidUtilMapCollections *)outer$;


@end

J2OBJC_EMPTY_STATIC_INIT(RepackagedAndroidUtilMapCollections_ValuesCollection)

FOUNDATION_EXPORT void RepackagedAndroidUtilMapCollections_ValuesCollection_initWithRepackagedAndroidUtilMapCollections_(RepackagedAndroidUtilMapCollections_ValuesCollection *self, RepackagedAndroidUtilMapCollections *outer$);

FOUNDATION_EXPORT RepackagedAndroidUtilMapCollections_ValuesCollection *new_RepackagedAndroidUtilMapCollections_ValuesCollection_initWithRepackagedAndroidUtilMapCollections_(RepackagedAndroidUtilMapCollections *outer$) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(RepackagedAndroidUtilMapCollections_ValuesCollection)

#endif // _RepackagedAndroidUtilMapCollections_H_
