//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/annotation/NonNull.java
//

#ifndef _RepackagedAndroidAnnotationNonNull_H_
#define _RepackagedAndroidAnnotationNonNull_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

/**
 @brief Denotes that a parameter, field or method return value can never be null.
 <p> This is a marker annotation and it has no specific attributes.
 */
@protocol RepackagedAndroidAnnotationNonNull < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(RepackagedAndroidAnnotationNonNull)

J2OBJC_TYPE_LITERAL_HEADER(RepackagedAndroidAnnotationNonNull)

#endif // _RepackagedAndroidAnnotationNonNull_H_
