//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/os/RemoteException.java
//


#include "J2ObjC_source.h"
#include "RemoteException.h"
#include "java/lang/Throwable.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/os/RemoteException.java"


#line 3
@implementation RepackagedAndroidOsRemoteException

- (instancetype)init {
  RepackagedAndroidOsRemoteException_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _RepackagedAndroidOsRemoteException = { 2, "RemoteException", "repackaged.android.os", NULL, 0x1, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_RepackagedAndroidOsRemoteException;
}

@end

void RepackagedAndroidOsRemoteException_init(RepackagedAndroidOsRemoteException *self) {
  (void) JavaLangThrowable_init(self);
}

RepackagedAndroidOsRemoteException *new_RepackagedAndroidOsRemoteException_init() {
  RepackagedAndroidOsRemoteException *self = [RepackagedAndroidOsRemoteException alloc];
  RepackagedAndroidOsRemoteException_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RepackagedAndroidOsRemoteException)
