//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/annotation/SuppressLint.java
//

#ifndef _RepackagedAndroidAnnotationSuppressLint_H_
#define _RepackagedAndroidAnnotationSuppressLint_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@class IOSObjectArray;

/**
 @brief Indicates that Lint should ignore the specified warnings for the annotated element.
 */
@protocol RepackagedAndroidAnnotationSuppressLint < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(RepackagedAndroidAnnotationSuppressLint)

J2OBJC_TYPE_LITERAL_HEADER(RepackagedAndroidAnnotationSuppressLint)

#endif // _RepackagedAndroidAnnotationSuppressLint_H_
