//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/annotation/AnimRes.java
//

#ifndef _RepackagedAndroidAnnotationAnimRes_H_
#define _RepackagedAndroidAnnotationAnimRes_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

/**
 @brief Denotes that an integer parameter, field or method return value is expected to be an anim resource reference (e.g. android.R.anim#fade_in ).
 */
@protocol RepackagedAndroidAnnotationAnimRes < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(RepackagedAndroidAnnotationAnimRes)

J2OBJC_TYPE_LITERAL_HEADER(RepackagedAndroidAnnotationAnimRes)

#endif // _RepackagedAndroidAnnotationAnimRes_H_
