//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/view/HapticFeedbackConstants.java
//


#include "HapticFeedbackConstants.h"
#include "J2ObjC_source.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/view/HapticFeedbackConstants.java"

@interface RepackagedAndroidViewHapticFeedbackConstants ()

- (instancetype)init;

@end

__attribute__((unused)) static void RepackagedAndroidViewHapticFeedbackConstants_init(RepackagedAndroidViewHapticFeedbackConstants *self);

__attribute__((unused)) static RepackagedAndroidViewHapticFeedbackConstants *new_RepackagedAndroidViewHapticFeedbackConstants_init() NS_RETURNS_RETAINED;


#line 23
@implementation RepackagedAndroidViewHapticFeedbackConstants

- (instancetype)init {
  RepackagedAndroidViewHapticFeedbackConstants_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "HapticFeedbackConstants", NULL, 0x2, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "LONG_PRESS_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = RepackagedAndroidViewHapticFeedbackConstants_LONG_PRESS },
    { "VIRTUAL_KEY_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = RepackagedAndroidViewHapticFeedbackConstants_VIRTUAL_KEY },
    { "KEYBOARD_TAP_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = RepackagedAndroidViewHapticFeedbackConstants_KEYBOARD_TAP },
    { "CLOCK_TICK_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = RepackagedAndroidViewHapticFeedbackConstants_CLOCK_TICK },
    { "CALENDAR_DATE_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = RepackagedAndroidViewHapticFeedbackConstants_CALENDAR_DATE },
    { "CONTEXT_CLICK_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = RepackagedAndroidViewHapticFeedbackConstants_CONTEXT_CLICK },
    { "SAFE_MODE_DISABLED_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = RepackagedAndroidViewHapticFeedbackConstants_SAFE_MODE_DISABLED },
    { "SAFE_MODE_ENABLED_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = RepackagedAndroidViewHapticFeedbackConstants_SAFE_MODE_ENABLED },
    { "FLAG_IGNORE_VIEW_SETTING_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = RepackagedAndroidViewHapticFeedbackConstants_FLAG_IGNORE_VIEW_SETTING },
    { "FLAG_IGNORE_GLOBAL_SETTING_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = RepackagedAndroidViewHapticFeedbackConstants_FLAG_IGNORE_GLOBAL_SETTING },
  };
  static const J2ObjcClassInfo _RepackagedAndroidViewHapticFeedbackConstants = { 2, "HapticFeedbackConstants", "repackaged.android.view", NULL, 0x1, 1, methods, 10, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_RepackagedAndroidViewHapticFeedbackConstants;
}

@end


#line 25
void RepackagedAndroidViewHapticFeedbackConstants_init(RepackagedAndroidViewHapticFeedbackConstants *self) {
  (void) NSObject_init(self);
}


#line 25
RepackagedAndroidViewHapticFeedbackConstants *new_RepackagedAndroidViewHapticFeedbackConstants_init() {
  RepackagedAndroidViewHapticFeedbackConstants *self = [RepackagedAndroidViewHapticFeedbackConstants alloc];
  RepackagedAndroidViewHapticFeedbackConstants_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RepackagedAndroidViewHapticFeedbackConstants)
