//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/view/HardwareLayer.java
//

#ifndef _RepackagedAndroidViewHardwareLayer_H_
#define _RepackagedAndroidViewHardwareLayer_H_

#include "J2ObjC_header.h"

@interface RepackagedAndroidViewHardwareLayer : NSObject

#pragma mark Public

- (instancetype)init;

- (jboolean)isValid;

@end

J2OBJC_EMPTY_STATIC_INIT(RepackagedAndroidViewHardwareLayer)

FOUNDATION_EXPORT void RepackagedAndroidViewHardwareLayer_init(RepackagedAndroidViewHardwareLayer *self);

FOUNDATION_EXPORT RepackagedAndroidViewHardwareLayer *new_RepackagedAndroidViewHardwareLayer_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(RepackagedAndroidViewHardwareLayer)

#endif // _RepackagedAndroidViewHardwareLayer_H_
