//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/dummyimpl/ios/HtmlImpl.java
//


#include "ContextWrapper.h"
#include "FrameLayout.h"
#include "HasWidgets.h"
#include "HtmlImpl.h"
#include "IWidget.h"
#include "J2ObjC_source.h"
#include "View.h"
#include "ViewGroup.h"
#include "java/io/PrintStream.h"
#include "java/lang/System.h"
#include "java/util/Iterator.h"
#include "java/util/Map.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/dummyimpl/ios/HtmlImpl.java"

@interface IosHtmlImpl ()

- (void)addToRootViewControllerWithInt:(jint)left
                               withInt:(jint)top
                               withInt:(jint)right
                               withInt:(jint)bottom;

- (jint)nativeGetScreenHeight;

- (jint)nativeGetScreenWidth;

- (void)nativeAddViewWithComAsheraAndroidWidgetFactoryIWidget:(id<ComAsheraAndroidWidgetFactoryIWidget>)w;

@end

__attribute__((unused)) static void IosHtmlImpl_addToRootViewControllerWithInt_withInt_withInt_withInt_(IosHtmlImpl *self, jint left, jint top, jint right, jint bottom);

__attribute__((unused)) static jint IosHtmlImpl_nativeGetScreenHeight(IosHtmlImpl *self);

__attribute__((unused)) static jint IosHtmlImpl_nativeGetScreenWidth(IosHtmlImpl *self);

__attribute__((unused)) static void IosHtmlImpl_nativeAddViewWithComAsheraAndroidWidgetFactoryIWidget_(IosHtmlImpl *self, id<ComAsheraAndroidWidgetFactoryIWidget> w);


#line 15
@implementation IosHtmlImpl


#line 16
- (instancetype)init {
  IosHtmlImpl_init(self);
  return self;
}


#line 22
- (void)addWithComAsheraAndroidWidgetFactoryIWidget:(id<ComAsheraAndroidWidgetFactoryIWidget>)w {
  if ([w isKindOfClass:[RepackagedAndroidViewView class]]) {
    [self addViewWithRepackagedAndroidViewView:((RepackagedAndroidViewView *) check_class_cast(w, [RepackagedAndroidViewView class]))];
    IosHtmlImpl_nativeAddViewWithComAsheraAndroidWidgetFactoryIWidget_(self, w);
  }
}


#line 30
- (void)clear {
  [self removeAllViews];
}


#line 35
- (id<JavaUtilIterator>)iterate {
  return nil;
}


#line 40
- (jboolean)removeWithComAsheraAndroidWidgetFactoryIWidget:(id<ComAsheraAndroidWidgetFactoryIWidget>)w {
  if ([w isKindOfClass:[RepackagedAndroidViewView class]]) {
    [self removeViewWithRepackagedAndroidViewView:((RepackagedAndroidViewView *) check_class_cast(w, [RepackagedAndroidViewView class]))];
    return YES;
  }
  return NO;
}


#line 49
- (id)asWidget {
  return [self nativeAsWidget];
}


#line 54
- (void)createWithJavaUtilMap:(id<JavaUtilMap>)metadata {
  [self nativeCreate];
}


#line 59
- (void)setParentWithComAsheraAndroidWidgetFactoryHasWidgets:(id<ComAsheraAndroidWidgetFactoryHasWidgets>)widget {
  mParent_ = (RepackagedAndroidViewViewGroup *) check_class_cast(widget, [RepackagedAndroidViewViewGroup class]);
}

- (void)measure {
  jint w = ((RepackagedAndroidViewViewGroup_LayoutParams *) nil_chk([self getLayoutParams]))->width_;
  jint h = ((RepackagedAndroidViewViewGroup_LayoutParams *) nil_chk([self getLayoutParams]))->height_;
  jint wmeasureSpec = RepackagedAndroidViewView_MeasureSpec_EXACTLY;
  jint hmeasureSpec = RepackagedAndroidViewView_MeasureSpec_EXACTLY;
  [self measureWithInt:RepackagedAndroidViewView_MeasureSpec_makeMeasureSpecWithInt_withInt_(w, wmeasureSpec) withInt:RepackagedAndroidViewView_MeasureSpec_makeMeasureSpecWithInt_withInt_(
#line 69
  h, hmeasureSpec)];
  [self layoutWithInt:0 withInt:0 withInt:IosHtmlImpl_nativeGetScreenWidth(self) withInt:IosHtmlImpl_nativeGetScreenHeight(self)];
}


#line 73
- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)left
                    withInt:(jint)top
                    withInt:(jint)right
                    withInt:(jint)bottom {
  [super onLayoutWithBoolean:changed withInt:left withInt:top withInt:right withInt:bottom];
  [((JavaIoPrintStream *) nil_chk(JavaLangSystem_get_out_())) printlnWithNSString:JreStrcat("ICICICI", left, ' ', top, ' ', right, ' ', bottom)];
  
#line 77
  IosHtmlImpl_addToRootViewControllerWithInt_withInt_withInt_withInt_(self, left, top, right, bottom);
}


#line 80
- (void)addToRootViewControllerWithInt:(jint)left
                               withInt:(jint)top
                               withInt:(jint)right
                               withInt:(jint)bottom {
  IosHtmlImpl_addToRootViewControllerWithInt_withInt_withInt_withInt_(self, left, top, right, bottom);
}


#line 88
- (jint)nativeGetScreenHeight {
  return IosHtmlImpl_nativeGetScreenHeight(self);
}


#line 91
- (jint)nativeGetScreenWidth {
  return IosHtmlImpl_nativeGetScreenWidth(self);
}

- (void)nativeAddViewWithComAsheraAndroidWidgetFactoryIWidget:(id<ComAsheraAndroidWidgetFactoryIWidget>)w {
  IosHtmlImpl_nativeAddViewWithComAsheraAndroidWidgetFactoryIWidget_(self, w);
}


#line 100
- (void)nativeCreate {
  self.htmlView = [UIView new];
}

- (id)nativeAsWidget {
  return self.htmlView;
}


#line 109
- (void)setParamWidthWithInt:(jint)width {
}


#line 115
- (void)setParamHeightWithInt:(jint)width {
}


#line 121
- (jint)getParamWidth {
  
#line 123
  return 0;
}

- (jint)getParamHeight {
  
#line 129
  return 0;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "HtmlImpl", NULL, 0x1, NULL, NULL },
    { "addWithComAsheraAndroidWidgetFactoryIWidget:", "add", "V", 0x1, NULL, NULL },
    { "clear", NULL, "V", 0x1, NULL, NULL },
    { "iterate", NULL, "Ljava.util.Iterator;", 0x1, NULL, NULL },
    { "removeWithComAsheraAndroidWidgetFactoryIWidget:", "remove", "Z", 0x1, NULL, NULL },
    { "asWidget", NULL, "Ljava.lang.Object;", 0x1, NULL, NULL },
    { "createWithJavaUtilMap:", "create", "V", 0x1, NULL, NULL },
    { "setParentWithComAsheraAndroidWidgetFactoryHasWidgets:", "setParent", "V", 0x1, NULL, NULL },
    { "measure", NULL, "V", 0x1, NULL, NULL },
    { "onLayoutWithBoolean:withInt:withInt:withInt:withInt:", "onLayout", "V", 0x4, NULL, NULL },
    { "addToRootViewControllerWithInt:withInt:withInt:withInt:", "addToRootViewController", "V", 0x102, NULL, NULL },
    { "nativeGetScreenHeight", NULL, "I", 0x102, NULL, NULL },
    { "nativeGetScreenWidth", NULL, "I", 0x102, NULL, NULL },
    { "nativeAddViewWithComAsheraAndroidWidgetFactoryIWidget:", "nativeAddView", "V", 0x102, NULL, NULL },
    { "nativeCreate", NULL, "V", 0x101, NULL, NULL },
    { "nativeAsWidget", NULL, "Ljava.lang.Object;", 0x101, NULL, NULL },
    { "setParamWidthWithInt:", "setParamWidth", "V", 0x1, NULL, NULL },
    { "setParamHeightWithInt:", "setParamHeight", "V", 0x1, NULL, NULL },
    { "getParamWidth", NULL, "I", 0x1, NULL, NULL },
    { "getParamHeight", NULL, "I", 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _IosHtmlImpl = { 2, "HtmlImpl", "ios", NULL, 0x1, 20, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_IosHtmlImpl;
}

@end


#line 16
void IosHtmlImpl_init(IosHtmlImpl *self) {
  (void) RepackagedAndroidWidgetFrameLayout_initWithRepackagedAndroidContentContext_(self, new_RepackagedAndroidContentContextWrapper_init());
  [self setLayoutParamsWithRepackagedAndroidViewViewGroup_LayoutParams:new_RepackagedAndroidWidgetFrameLayout_LayoutParams_initWithInt_withInt_(IosHtmlImpl_nativeGetScreenWidth(self), IosHtmlImpl_nativeGetScreenHeight(self))];
}


#line 16
IosHtmlImpl *new_IosHtmlImpl_init() {
  IosHtmlImpl *self = [IosHtmlImpl alloc];
  IosHtmlImpl_init(self);
  return self;
}


#line 80
void IosHtmlImpl_addToRootViewControllerWithInt_withInt_withInt_withInt_(IosHtmlImpl *self, jint left, jint top, jint right, jint bottom) {
  self.htmlView.backgroundColor = [UIColor redColor];
  [self.htmlView setFrame:CGRectMake(left, top, right-left, bottom-top)];
  
  UIWindow* window = [[[UIApplication sharedApplication] delegate] window];
  [window.rootViewController.view addSubview:self.htmlView];
}

jint IosHtmlImpl_nativeGetScreenHeight(IosHtmlImpl *self) {
  return [UIScreen mainScreen].bounds.size.height;
}


#line 91
jint IosHtmlImpl_nativeGetScreenWidth(IosHtmlImpl *self) {
  return [UIScreen mainScreen].bounds.size.width;
}

void IosHtmlImpl_nativeAddViewWithComAsheraAndroidWidgetFactoryIWidget_(IosHtmlImpl *self, id<ComAsheraAndroidWidgetFactoryIWidget> w) {
  [self.htmlView addSubview:[w asWidget]];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(IosHtmlImpl)
