//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/dummyimpl/ios/HtmlViewerUtils.java
//

#ifndef _IosHtmlViewerUtils_H_
#define _IosHtmlViewerUtils_H_

#include "J2ObjC_header.h"

@protocol JavaUtilMap;

@interface IosHtmlViewerUtils : NSObject

#pragma mark Public

- (instancetype)init;

+ (id)displayHtmlWithNSString:(NSString *)assetHtml
              withJavaUtilMap:(id<JavaUtilMap>)metadata;

@end

J2OBJC_STATIC_INIT(IosHtmlViewerUtils)

FOUNDATION_EXPORT id IosHtmlViewerUtils_displayHtmlWithNSString_withJavaUtilMap_(NSString *assetHtml, id<JavaUtilMap> metadata);

FOUNDATION_EXPORT void IosHtmlViewerUtils_init(IosHtmlViewerUtils *self);

FOUNDATION_EXPORT IosHtmlViewerUtils *new_IosHtmlViewerUtils_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(IosHtmlViewerUtils)

#endif // _IosHtmlViewerUtils_H_
