//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/util/LayoutDirection.java
//


#include "J2ObjC_source.h"
#include "LayoutDirection.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/util/LayoutDirection.java"

@interface RepackagedAndroidUtilLayoutDirection ()

- (instancetype)init;

@end

__attribute__((unused)) static void RepackagedAndroidUtilLayoutDirection_init(RepackagedAndroidUtilLayoutDirection *self);

__attribute__((unused)) static RepackagedAndroidUtilLayoutDirection *new_RepackagedAndroidUtilLayoutDirection_init() NS_RETURNS_RETAINED;


#line 24
@implementation RepackagedAndroidUtilLayoutDirection


#line 27
- (instancetype)init {
  RepackagedAndroidUtilLayoutDirection_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "LayoutDirection", NULL, 0x2, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "UNDEFINED_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = RepackagedAndroidUtilLayoutDirection_UNDEFINED },
    { "LTR_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = RepackagedAndroidUtilLayoutDirection_LTR },
    { "RTL_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = RepackagedAndroidUtilLayoutDirection_RTL },
    { "INHERIT_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = RepackagedAndroidUtilLayoutDirection_INHERIT },
    { "LOCALE_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = RepackagedAndroidUtilLayoutDirection_LOCALE },
  };
  static const J2ObjcClassInfo _RepackagedAndroidUtilLayoutDirection = { 2, "LayoutDirection", "repackaged.android.util", NULL, 0x11, 1, methods, 5, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_RepackagedAndroidUtilLayoutDirection;
}

@end


#line 27
void RepackagedAndroidUtilLayoutDirection_init(RepackagedAndroidUtilLayoutDirection *self) {
  (void) NSObject_init(self);
}


#line 27
RepackagedAndroidUtilLayoutDirection *new_RepackagedAndroidUtilLayoutDirection_init() {
  RepackagedAndroidUtilLayoutDirection *self = [RepackagedAndroidUtilLayoutDirection alloc];
  RepackagedAndroidUtilLayoutDirection_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RepackagedAndroidUtilLayoutDirection)
