//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/annotation/PluralsRes.java
//

#ifndef _RepackagedAndroidAnnotationPluralsRes_H_
#define _RepackagedAndroidAnnotationPluralsRes_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

/**
 @brief Denotes that an integer parameter, field or method return value is expected to be a plurals resource reference.
 */
@protocol RepackagedAndroidAnnotationPluralsRes < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(RepackagedAndroidAnnotationPluralsRes)

J2OBJC_TYPE_LITERAL_HEADER(RepackagedAndroidAnnotationPluralsRes)

#endif // _RepackagedAndroidAnnotationPluralsRes_H_
