//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/util/Printer.java
//


#include "J2ObjC_source.h"
#include "Printer.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/util/Printer.java"

@interface RepackagedAndroidUtilPrinter : NSObject
@end


#line 25
@implementation RepackagedAndroidUtilPrinter

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "printlnWithNSString:", "println", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _RepackagedAndroidUtilPrinter = { 2, "Printer", "repackaged.android.util", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_RepackagedAndroidUtilPrinter;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RepackagedAndroidUtilPrinter)
