//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/os/Process.java
//


#include "J2ObjC_source.h"
#include "Process.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/androidlayouts/repackaged/android/os/Process.java"


#line 3
@implementation RepackagedAndroidOsProcess

- (instancetype)init {
  RepackagedAndroidOsProcess_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _RepackagedAndroidOsProcess = { 2, "Process", "repackaged.android.os", NULL, 0x1, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_RepackagedAndroidOsProcess;
}

@end

void RepackagedAndroidOsProcess_init(RepackagedAndroidOsProcess *self) {
  (void) NSObject_init(self);
}

RepackagedAndroidOsProcess *new_RepackagedAndroidOsProcess_init() {
  RepackagedAndroidOsProcess *self = [RepackagedAndroidOsProcess alloc];
  RepackagedAndroidOsProcess_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RepackagedAndroidOsProcess)
