//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/cssparser/repackaged/org/w3c/css/sac/CharacterDataSelector.java
//


#include "CharacterDataSelector.h"
#include "J2ObjC_source.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/cssparser/repackaged/org/w3c/css/sac/CharacterDataSelector.java"

@interface RepackagedOrgW3cCssSacCharacterDataSelector : NSObject
@end


#line 18
@implementation RepackagedOrgW3cCssSacCharacterDataSelector

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getData", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _RepackagedOrgW3cCssSacCharacterDataSelector = { 2, "CharacterDataSelector", "repackaged.org.w3c.css.sac", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_RepackagedOrgW3cCssSacCharacterDataSelector;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RepackagedOrgW3cCssSacCharacterDataSelector)
