//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/cssparser/repackaged/org/w3c/css/sac/ConditionalSelector.java
//

#ifndef _RepackagedOrgW3cCssSacConditionalSelector_H_
#define _RepackagedOrgW3cCssSacConditionalSelector_H_

#include "J2ObjC_header.h"
#include "SimpleSelector.h"

@protocol RepackagedOrgW3cCssSacCondition;

/**
 @version $Revision: 1.2 $
 @author Philippe Le Hegaret
 */
@protocol RepackagedOrgW3cCssSacConditionalSelector < RepackagedOrgW3cCssSacSimpleSelector, NSObject, JavaObject >

/**
 @brief Returns the simple selector.
 <p>The simple selector can't be a <code>ConditionalSelector</code>.</p>
 */
- (id<RepackagedOrgW3cCssSacSimpleSelector>)getSimpleSelector;

/**
 @brief Returns the condition to be applied on the simple selector.
 */
- (id<RepackagedOrgW3cCssSacCondition>)getCondition;

@end

J2OBJC_EMPTY_STATIC_INIT(RepackagedOrgW3cCssSacConditionalSelector)

J2OBJC_TYPE_LITERAL_HEADER(RepackagedOrgW3cCssSacConditionalSelector)

#endif // _RepackagedOrgW3cCssSacConditionalSelector_H_
