//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/cssparser/repackaged/org/w3c/css/sac/DocumentHandler.java
//

#ifndef _RepackagedOrgW3cCssSacDocumentHandler_H_
#define _RepackagedOrgW3cCssSacDocumentHandler_H_

#include "J2ObjC_header.h"

@class RepackagedOrgW3cCssSacInputSource;
@protocol RepackagedOrgW3cCssSacLexicalUnit;
@protocol RepackagedOrgW3cCssSacSACMediaList;
@protocol RepackagedOrgW3cCssSacSelectorList;

/**
 @brief This is the main interface that most CSS applications implement: if the application needs to be informed of basic parsing events, it implements this interface and registers an instance with the CSS parser using the setCSSHandler method.
 @version $Revision: 1.4 $
 @author Philippe Le Hegaret
 */
@protocol RepackagedOrgW3cCssSacDocumentHandler < NSObject, JavaObject >

/**
 @brief Receive notification of the beginning of a style sheet.
 The CSS parser will invoke this method only once, before any other methods in this interface.
 @param uri The URI of the style sheet. @@@@TODO can be NULL ! (inline style sheet)
 @exception CSSException Any CSS exception, possibly wrapping another exception.
 */
- (void)startDocumentWithRepackagedOrgW3cCssSacInputSource:(RepackagedOrgW3cCssSacInputSource *)source;

/**
 @brief Receive notification of the end of a document.
 The CSS parser will invoke this method only once, and it will be the last method invoked during the parse. The parser shall not invoke this method until it has either abandoned parsing (because of an unrecoverable error) or reached the end of input.
 @param uri The URI of the style sheet.
 @exception CSSException Any CSS exception, possibly wrapping another exception.
 */
- (void)endDocumentWithRepackagedOrgW3cCssSacInputSource:(RepackagedOrgW3cCssSacInputSource *)source;

/**
 @brief Receive notification of a comment.
 If the comment appears in a declaration (e.g. color: /\* comment * / blue;), the parser notifies the comment before the declaration.
 @param text The comment.
 @exception CSSException Any CSS exception, possibly wrapping another exception.
 */
- (void)commentWithNSString:(NSString *)text;

/**
 @brief Receive notification of an unknown rule t-rule not supported by this parser.
 @param at-rule The complete ignored at-rule.
 @exception CSSException Any CSS exception, possibly wrapping another exception.
 */
- (void)ignorableAtRuleWithNSString:(NSString *)atRule;

/**
 @brief Receive notification of an unknown rule t-rule not supported by this parser.
 @param prefix <code>null</code> if this is the default namespace
 @param uri The URI for this namespace.
 @exception CSSException Any CSS exception, possibly wrapping another exception.
 */
- (void)namespaceDeclarationWithNSString:(NSString *)prefix
                            withNSString:(NSString *)uri;

/**
 @brief Receive notification of a import statement in the style sheet.
 @param uri The URI of the imported style sheet.
 @param media The intended destination media for style information.
 @param defaultNamepaceURI The default namespace URI for the imported style sheet.
 @exception CSSException Any CSS exception, possibly wrapping another exception.
 */
- (void)importStyleWithNSString:(NSString *)uri
withRepackagedOrgW3cCssSacSACMediaList:(id<RepackagedOrgW3cCssSacSACMediaList>)media
                   withNSString:(NSString *)defaultNamespaceURI;

/**
 @brief Receive notification of the beginning of a media statement.
 The Parser will invoke this method at the beginning of every media statement in the style sheet. there will be a corresponding endMedia() event for every startElement() event.
 @param media The intended destination media for style information.
 @exception CSSException Any CSS exception, possibly wrapping another exception.
 */
- (void)startMediaWithRepackagedOrgW3cCssSacSACMediaList:(id<RepackagedOrgW3cCssSacSACMediaList>)media;

/**
 @brief Receive notification of the end of a media statement.
 @param media The intended destination media for style information.
 @exception CSSException Any CSS exception, possibly wrapping another exception.
 */
- (void)endMediaWithRepackagedOrgW3cCssSacSACMediaList:(id<RepackagedOrgW3cCssSacSACMediaList>)media;

/**
 @brief Receive notification of the beginning of a page statement.
 The Parser will invoke this method at the beginning of every page statement in the style sheet. there will be a corresponding endPage() event for every startPage() event.
 @param name the name of the page (if any, null otherwise)
 @param pseudo_page the pseudo page (if any, null otherwise)
 @exception CSSException Any CSS exception, possibly wrapping another exception.
 */
- (void)startPageWithNSString:(NSString *)name
                 withNSString:(NSString *)pseudo_page;

/**
 @brief Receive notification of the end of a media statement.
 @param media The intended destination medium for style information.
 @param pseudo_page the pseudo page (if any, null otherwise)
 @exception CSSException Any CSS exception, possibly wrapping another exception.
 */
- (void)endPageWithNSString:(NSString *)name
               withNSString:(NSString *)pseudo_page;

/**
 @brief Receive notification of the beginning of a font face statement.
 The Parser will invoke this method at the beginning of every font face statement in the style sheet. there will be a corresponding endFontFace() event for every startFontFace() event.
 @exception CSSException Any CSS exception, possibly wrapping another exception.
 */
- (void)startFontFace;

/**
 @brief Receive notification of the end of a font face statement.
 @exception CSSException Any CSS exception, possibly wrapping another exception.
 */
- (void)endFontFace;

/**
 @brief Receive notification of the beginning of a rule statement.
 @param selectors All intended selectors for all declarations.
 @exception CSSException Any CSS exception, possibly wrapping another exception.
 */
- (void)startSelectorWithRepackagedOrgW3cCssSacSelectorList:(id<RepackagedOrgW3cCssSacSelectorList>)selectors;

/**
 @brief Receive notification of the end of a rule statement.
 @param selectors All intended selectors for all declarations.
 @exception CSSException Any CSS exception, possibly wrapping another exception.
 */
- (void)endSelectorWithRepackagedOrgW3cCssSacSelectorList:(id<RepackagedOrgW3cCssSacSelectorList>)selectors;

/**
 @brief Receive notification of a declaration.
 @param name the name of the property.
 @param value the value of the property. All whitespace are stripped.
 @param important is this property important ?
 @exception CSSException Any CSS exception, possibly wrapping another exception.
 */
- (void)propertyWithNSString:(NSString *)name
withRepackagedOrgW3cCssSacLexicalUnit:(id<RepackagedOrgW3cCssSacLexicalUnit>)value
                 withBoolean:(jboolean)important;

@end

J2OBJC_EMPTY_STATIC_INIT(RepackagedOrgW3cCssSacDocumentHandler)

J2OBJC_TYPE_LITERAL_HEADER(RepackagedOrgW3cCssSacDocumentHandler)

#endif // _RepackagedOrgW3cCssSacDocumentHandler_H_
