//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/cssparser/repackaged/org/w3c/css/sac/ErrorHandler.java
//


#include "CSSException.h"
#include "CSSParseException.h"
#include "ErrorHandler.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/cssparser/repackaged/org/w3c/css/sac/ErrorHandler.java"

@interface RepackagedOrgW3cCssSacErrorHandler : NSObject
@end


#line 40
@implementation RepackagedOrgW3cCssSacErrorHandler

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "warningWithRepackagedOrgW3cCssSacCSSParseException:", "warning", "V", 0x401, "Lrepackaged.org.w3c.css.sac.CSSException;", NULL },
    { "errorWithRepackagedOrgW3cCssSacCSSParseException:", "error", "V", 0x401, "Lrepackaged.org.w3c.css.sac.CSSException;", NULL },
    { "fatalErrorWithRepackagedOrgW3cCssSacCSSParseException:", "fatalError", "V", 0x401, "Lrepackaged.org.w3c.css.sac.CSSException;", NULL },
  };
  static const J2ObjcClassInfo _RepackagedOrgW3cCssSacErrorHandler = { 2, "ErrorHandler", "repackaged.org.w3c.css.sac", NULL, 0x609, 3, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_RepackagedOrgW3cCssSacErrorHandler;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RepackagedOrgW3cCssSacErrorHandler)
