//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/cssparser/com/steadystate/css/parser/LocatorImpl.java
//


#include "J2ObjC_source.h"
#include "LangUtils.h"
#include "Locator.h"
#include "LocatorImpl.h"
#include "java/lang/StringBuilder.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/cssparser/com/steadystate/css/parser/LocatorImpl.java"

#define ComSteadystateCssParserLocatorImpl_serialVersionUID 2240824537064705530LL

@interface ComSteadystateCssParserLocatorImpl () {
 @public
  NSString *uri__;
  jint lineNumber__;
  jint columnNumber__;
}

@end

J2OBJC_FIELD_SETTER(ComSteadystateCssParserLocatorImpl, uri__, NSString *)

J2OBJC_STATIC_FIELD_GETTER(ComSteadystateCssParserLocatorImpl, serialVersionUID, jlong)


#line 40
@implementation ComSteadystateCssParserLocatorImpl


#line 54
- (instancetype)initWithNSString:(NSString *)uri
                         withInt:(jint)line
                         withInt:(jint)column {
  ComSteadystateCssParserLocatorImpl_initWithNSString_withInt_withInt_(self, uri, line, column);
  return self;
}


#line 69
- (NSString *)getURI {
  return uri__;
}


#line 76
- (NSString *)getUri {
  return uri__;
}


#line 85
- (void)setUriWithNSString:(NSString *)uri {
  uri__ = uri;
}


#line 97
- (jint)getColumnNumber {
  return columnNumber__;
}


#line 105
- (void)setColumnNumberWithInt:(jint)column {
  columnNumber__ = column;
}


#line 116
- (jint)getLineNumber {
  return lineNumber__;
}


#line 124
- (void)setLineNumberWithInt:(jint)line {
  lineNumber__ = line;
}


#line 129
- (jboolean)isEqual:(id)obj {
  if (self == obj) {
    return YES;
  }
  if (!([RepackagedOrgW3cCssSacLocator_class_() isInstance:obj])) {
    return NO;
  }
  id<RepackagedOrgW3cCssSacLocator> l = (id<RepackagedOrgW3cCssSacLocator>) check_protocol_cast(obj, @protocol(RepackagedOrgW3cCssSacLocator));
  return ([self getColumnNumber] == [((id<RepackagedOrgW3cCssSacLocator>) nil_chk(l)) getColumnNumber]) &&
#line 138
  ([self getLineNumber] == [l getLineNumber]) && ComSteadystateCssUtilLangUtils_equalsWithId_withId_(
#line 139
  [self getURI], [l getURI]);
}


#line 143
- (NSUInteger)hash {
  jint hash_ = ComSteadystateCssUtilLangUtils_HASH_SEED;
  hash_ = ComSteadystateCssUtilLangUtils_hashCodeWithInt_withInt_(hash_, columnNumber__);
  hash_ = ComSteadystateCssUtilLangUtils_hashCodeWithInt_withInt_(hash_, lineNumber__);
  hash_ = ComSteadystateCssUtilLangUtils_hashCodeWithInt_withId_(hash_, uri__);
  return hash_;
}


#line 152
- (NSString *)description {
  return [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([new_JavaLangStringBuilder_init() appendWithNSString:[self getUri]])) appendWithNSString:@" ("])) appendWithInt:
#line 154
  [self getLineNumber]])) appendWithChar:':'])) appendWithInt:
#line 155
  [self getColumnNumber]])) appendWithChar:')'])) description];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withInt:withInt:", "LocatorImpl", NULL, 0x1, NULL, NULL },
    { "getURI", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getUri", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "setUriWithNSString:", "setUri", "V", 0x1, NULL, NULL },
    { "getColumnNumber", NULL, "I", 0x1, NULL, NULL },
    { "setColumnNumberWithInt:", "setColumnNumber", "V", 0x1, NULL, NULL },
    { "getLineNumber", NULL, "I", 0x1, NULL, NULL },
    { "setLineNumberWithInt:", "setLineNumber", "V", 0x1, NULL, NULL },
    { "isEqual:", "equals", "Z", 0x1, NULL, NULL },
    { "hash", "hashCode", "I", 0x1, NULL, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID_", NULL, 0x1a, "J", NULL, NULL, .constantValue.asLong = ComSteadystateCssParserLocatorImpl_serialVersionUID },
    { "uri__", NULL, 0x2, "Ljava.lang.String;", NULL, NULL,  },
    { "lineNumber__", NULL, 0x2, "I", NULL, NULL,  },
    { "columnNumber__", NULL, 0x2, "I", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _ComSteadystateCssParserLocatorImpl = { 2, "LocatorImpl", "com.steadystate.css.parser", NULL, 0x1, 11, methods, 4, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComSteadystateCssParserLocatorImpl;
}

@end


#line 54
void ComSteadystateCssParserLocatorImpl_initWithNSString_withInt_withInt_(ComSteadystateCssParserLocatorImpl *self, NSString *uri, jint line, jint column) {
  (void) NSObject_init(self);
  
#line 55
  self->uri__ = uri;
  self->lineNumber__ = line;
  self->columnNumber__ = column;
}


#line 54
ComSteadystateCssParserLocatorImpl *new_ComSteadystateCssParserLocatorImpl_initWithNSString_withInt_withInt_(NSString *uri, jint line, jint column) {
  ComSteadystateCssParserLocatorImpl *self = [ComSteadystateCssParserLocatorImpl alloc];
  ComSteadystateCssParserLocatorImpl_initWithNSString_withInt_withInt_(self, uri, line, column);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComSteadystateCssParserLocatorImpl)
