//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/cssparser/com/steadystate/css/parser/ParserUtils.java
//


#include "J2ObjC_source.h"
#include "ParserUtils.h"
#include "java/lang/StringBuilder.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/cssparser/com/steadystate/css/parser/ParserUtils.java"

@interface ComSteadystateCssParserParserUtils ()

- (instancetype)init;

@end

__attribute__((unused)) static void ComSteadystateCssParserParserUtils_init(ComSteadystateCssParserParserUtils *self);

__attribute__((unused)) static ComSteadystateCssParserParserUtils *new_ComSteadystateCssParserParserUtils_init() NS_RETURNS_RETAINED;


#line 33
@implementation ComSteadystateCssParserParserUtils

- (instancetype)init {
  ComSteadystateCssParserParserUtils_init(self);
  return self;
}


#line 47
+ (NSString *)trimByWithJavaLangStringBuilder:(JavaLangStringBuilder *)s
                                      withInt:(jint)left
                                      withInt:(jint)right {
  return ComSteadystateCssParserParserUtils_trimByWithJavaLangStringBuilder_withInt_withInt_(s, left, right);
}


#line 57
+ (NSString *)trimUrlWithJavaLangStringBuilder:(JavaLangStringBuilder *)s {
  return ComSteadystateCssParserParserUtils_trimUrlWithJavaLangStringBuilder_(s);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "ParserUtils", NULL, 0x2, NULL, NULL },
    { "trimByWithJavaLangStringBuilder:withInt:withInt:", "trimBy", "Ljava.lang.String;", 0x9, NULL, NULL },
    { "trimUrlWithJavaLangStringBuilder:", "trimUrl", "Ljava.lang.String;", 0x9, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComSteadystateCssParserParserUtils = { 2, "ParserUtils", "com.steadystate.css.parser", NULL, 0x11, 3, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComSteadystateCssParserParserUtils;
}

@end


#line 35
void ComSteadystateCssParserParserUtils_init(ComSteadystateCssParserParserUtils *self) {
  (void) NSObject_init(self);
}


#line 35
ComSteadystateCssParserParserUtils *new_ComSteadystateCssParserParserUtils_init() {
  ComSteadystateCssParserParserUtils *self = [ComSteadystateCssParserParserUtils alloc];
  ComSteadystateCssParserParserUtils_init(self);
  return self;
}


#line 47
NSString *ComSteadystateCssParserParserUtils_trimByWithJavaLangStringBuilder_withInt_withInt_(JavaLangStringBuilder *s, jint left, jint right) {
  ComSteadystateCssParserParserUtils_initialize();
  
#line 48
  return [s substringWithInt:left withInt:[((JavaLangStringBuilder *) nil_chk(s)) length] - right];
}


#line 57
NSString *ComSteadystateCssParserParserUtils_trimUrlWithJavaLangStringBuilder_(JavaLangStringBuilder *s) {
  ComSteadystateCssParserParserUtils_initialize();
  
#line 58
  NSString *s1 = [((NSString *) nil_chk(ComSteadystateCssParserParserUtils_trimByWithJavaLangStringBuilder_withInt_withInt_(s, 4, 1))) trim];
  if (((jint) [((NSString *) nil_chk(s1)) length]) == 0) {
    return s1;
  }
  
#line 63
  jint end = ((jint) [s1 length]) - 1;
  jchar c0 = [s1 charAtWithInt:0];
  if ((c0 == '"' && [s1 charAtWithInt:end] == '"') ||
#line 66
  (c0 == '\'' && [s1 charAtWithInt:end] == '\'')) {
    return [s1 substring:1 endIndex:end];
  }
  
#line 70
  return s1;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComSteadystateCssParserParserUtils)
