//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/src/com/ashera/widget/BaseHasWidgets.java
//

#ifndef _ComAsheraWidgetBaseHasWidgets_H_
#define _ComAsheraWidgetBaseHasWidgets_H_

#include "BaseWidget.h"
#include "HasWidgets.h"
#include "J2ObjC_header.h"

@protocol ComAsheraWidgetFactoryIWidget;
@protocol JavaUtilIterator;

@interface ComAsheraWidgetBaseHasWidgets : ComAsheraWidgetBaseWidget < ComAsheraWidgetFactoryHasWidgets >

#pragma mark Public

- (instancetype)init;

- (void)addWithComAsheraWidgetFactoryIWidget:(id<ComAsheraWidgetFactoryIWidget>)w;

- (void)clear;

- (id<JavaUtilIterator>)iterate;

- (jboolean)removeWithComAsheraWidgetFactoryIWidget:(id<ComAsheraWidgetFactoryIWidget>)w;

@end

J2OBJC_EMPTY_STATIC_INIT(ComAsheraWidgetBaseHasWidgets)

FOUNDATION_EXPORT void ComAsheraWidgetBaseHasWidgets_init(ComAsheraWidgetBaseHasWidgets *self);

J2OBJC_TYPE_LITERAL_HEADER(ComAsheraWidgetBaseHasWidgets)

#endif // _ComAsheraWidgetBaseHasWidgets_H_
