//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/src/com/ashera/android/widget/factory/Button.java
//


#include "Button.h"
#include "J2ObjC_source.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/src/com/ashera/android/widget/factory/Button.java"

@interface ComAsheraAndroidWidgetFactoryButton : NSObject
@end


#line 3
@implementation ComAsheraAndroidWidgetFactoryButton

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _ComAsheraAndroidWidgetFactoryButton = { 2, "Button", "com.ashera.android.widget.factory", NULL, 0x609, 0, NULL, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComAsheraAndroidWidgetFactoryButton;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComAsheraAndroidWidgetFactoryButton)
