//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/src/com/ashera/android/parser/factory/CssParserFactory.java
//

#ifndef _ComAsheraAndroidParserFactoryCssParserFactory_H_
#define _ComAsheraAndroidParserFactoryCssParserFactory_H_

#include "J2ObjC_header.h"

@protocol ComAsheraAndroidParserFactoryCssParser;

@interface ComAsheraAndroidParserFactoryCssParserFactory : NSObject

#pragma mark Public

- (instancetype)init;

- (id<ComAsheraAndroidParserFactoryCssParser>)getParser;

@end

J2OBJC_EMPTY_STATIC_INIT(ComAsheraAndroidParserFactoryCssParserFactory)

FOUNDATION_EXPORT void ComAsheraAndroidParserFactoryCssParserFactory_init(ComAsheraAndroidParserFactoryCssParserFactory *self);

FOUNDATION_EXPORT ComAsheraAndroidParserFactoryCssParserFactory *new_ComAsheraAndroidParserFactoryCssParserFactory_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComAsheraAndroidParserFactoryCssParserFactory)

#endif // _ComAsheraAndroidParserFactoryCssParserFactory_H_
