//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/src/com/ashera/widget/factory/ILabel.java
//


#include "ILabel.h"
#include "J2ObjC_source.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/src/com/ashera/widget/factory/ILabel.java"

@interface ComAsheraWidgetFactoryILabel : NSObject
@end


#line 3
@implementation ComAsheraWidgetFactoryILabel

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _ComAsheraWidgetFactoryILabel = { 2, "ILabel", "com.ashera.widget.factory", NULL, 0x609, 0, NULL, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComAsheraWidgetFactoryILabel;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComAsheraWidgetFactoryILabel)
