//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/src/com/ashera/android/widget/factory/ILabel.java
//


#include "ILabel.h"
#include "J2ObjC_source.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/src/com/ashera/android/widget/factory/ILabel.java"

@interface ComAsheraAndroidWidgetFactoryILabel : NSObject
@end


#line 3
@implementation ComAsheraAndroidWidgetFactoryILabel

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "setColorWithNSString:", "setColor", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComAsheraAndroidWidgetFactoryILabel = { 2, "ILabel", "com.ashera.android.widget.factory", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComAsheraAndroidWidgetFactoryILabel;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComAsheraAndroidWidgetFactoryILabel)
