//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/src/com/ashera/android/widget/factory/IWidget.java
//


#include "IWidget.h"
#include "J2ObjC_source.h"

#line 0 "/Users/ramm/git/Ashera/AsheraAndroidParser/src/com/ashera/android/widget/factory/IWidget.java"

@interface ComAsheraAndroidWidgetFactoryIWidget : NSObject
@end


#line 3
@implementation ComAsheraAndroidWidgetFactoryIWidget

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _ComAsheraAndroidWidgetFactoryIWidget = { 2, "IWidget", "com.ashera.android.widget.factory", NULL, 0x609, 0, NULL, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComAsheraAndroidWidgetFactoryIWidget;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComAsheraAndroidWidgetFactoryIWidget)
