//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ramm/git/Ashera/AsheraAndroidParser/src/com/ashera/widget/LinkWidget.java
//

#ifndef _ComAsheraWidgetLinkWidget_H_
#define _ComAsheraWidgetLinkWidget_H_

#include "IWidget.h"
#include "J2ObjC_header.h"

@class IOSObjectArray;
@protocol ComAsheraWidgetFactoryHasWidgets;
@protocol JavaUtilMap;

@interface ComAsheraWidgetLinkWidget : NSObject < ComAsheraWidgetFactoryIWidget >

#pragma mark Public

- (instancetype)init;

- (id)asNativeWidget;

- (id)asWidget;

- (void)createWithJavaUtilMap:(id<JavaUtilMap>)metadata;

- (IOSObjectArray *)getAttributes;

- (id)getAttributeValueWithNSString:(NSString *)attr;

- (id<ComAsheraWidgetFactoryIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (void)setParentWithComAsheraWidgetFactoryHasWidgets:(id<ComAsheraWidgetFactoryHasWidgets>)widget;

- (void)setUpAttributeWithJavaUtilMap:(id<JavaUtilMap>)attributes;

- (void)setUpStyleWithJavaUtilMap:(id<JavaUtilMap>)styles;

@end

J2OBJC_EMPTY_STATIC_INIT(ComAsheraWidgetLinkWidget)

FOUNDATION_EXPORT void ComAsheraWidgetLinkWidget_init(ComAsheraWidgetLinkWidget *self);

FOUNDATION_EXPORT ComAsheraWidgetLinkWidget *new_ComAsheraWidgetLinkWidget_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComAsheraWidgetLinkWidget)

#endif // _ComAsheraWidgetLinkWidget_H_
